// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Metal\MTL\MTLBuffer;

class MTLBuffer
{
    public static function length(int handle) -> int
    {
        return mtlbuffer_length(handle);
    }

    public static function contentsBytes(int handle, int offset, int length) -> string
    {
        var result;

        let result = mtlbuffer_contents_bytes(handle, offset, length);

        return result;
    }

    public static function setContentsBytes(int handle, string bytes, int offset) -> bool
    {
        int r;

        let r = mtlbuffer_set_contents_bytes(handle, bytes, offset);

        return r == 1;
    }
}
