// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Metal\MTL\MTLCommandQueue;

class MTLCommandQueue
{
    public static function commandBuffer(int handle) -> int
    {
        return mtlcommandqueue_command_buffer(handle);
    }

    public static function label(int handle) -> var
    {
        var result;

        let result = mtlcommandqueue_label(handle);

        return result;
    }

    public static function setLabel(int handle, var label) -> void
    {
        mtlcommandqueue_set_label(handle, label);
    }
}
