// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Metal\MTL\MTLVertexAttributeDescriptor;

class MTLVertexAttributeDescriptor
{
    public static function format(int handle) -> int
    {
        return mtlvertexattributedescriptor_format(handle);
    }

    public static function setFormat(int handle, int format) -> void
    {
        mtlvertexattributedescriptor_set_format(handle, format);
    }

    public static function offset(int handle) -> int
    {
        return mtlvertexattributedescriptor_offset(handle);
    }

    public static function setOffset(int handle, int offset) -> void
    {
        mtlvertexattributedescriptor_set_offset(handle, offset);
    }

    public static function bufferIndex(int handle) -> int
    {
        return mtlvertexattributedescriptor_buffer_index(handle);
    }

    public static function setBufferIndex(int handle, int bufferIndex) -> void
    {
        mtlvertexattributedescriptor_set_buffer_index(handle, bufferIndex);
    }
}
