// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Metal\MTL\MTLRenderPassAttachmentDescriptor;

class MTLRenderPassAttachmentDescriptor
{
    public static function texture(int handle) -> int
    {
        return mtlrenderpassattachmentdescriptor_texture(handle);
    }

    public static function setTexture(int handle, int texture) -> void
    {
        mtlrenderpassattachmentdescriptor_set_texture(handle, texture);
    }

    public static function loadAction(int handle) -> int
    {
        return mtlrenderpassattachmentdescriptor_load_action(handle);
    }

    public static function setLoadAction(int handle, int loadAction) -> void
    {
        mtlrenderpassattachmentdescriptor_set_load_action(handle, loadAction);
    }

    public static function storeAction(int handle) -> int
    {
        return mtlrenderpassattachmentdescriptor_store_action(handle);
    }

    public static function setStoreAction(int handle, int storeAction) -> void
    {
        mtlrenderpassattachmentdescriptor_set_store_action(handle, storeAction);
    }
}
