// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Metal\MTL\MTLRenderPipelineDescriptor;

class MTLRenderPipelineDescriptor
{
    public static function init() -> int
    {
        return mtlrenderpipelinedescriptor_init();
    }

    public static function vertexFunction(int handle) -> int
    {
        return mtlrenderpipelinedescriptor_vertex_function(handle);
    }

    public static function setVertexFunction(int handle, int vertexFunction) -> void
    {
        mtlrenderpipelinedescriptor_set_vertex_function(handle, vertexFunction);
    }

    public static function fragmentFunction(int handle) -> int
    {
        return mtlrenderpipelinedescriptor_fragment_function(handle);
    }

    public static function setFragmentFunction(int handle, int fragmentFunction) -> void
    {
        mtlrenderpipelinedescriptor_set_fragment_function(handle, fragmentFunction);
    }

    public static function vertexDescriptor(int handle) -> int
    {
        return mtlrenderpipelinedescriptor_vertex_descriptor(handle);
    }

    public static function setVertexDescriptor(int handle, int vertexDescriptor) -> void
    {
        mtlrenderpipelinedescriptor_set_vertex_descriptor(handle, vertexDescriptor);
    }

    public static function rasterSampleCount(int handle) -> int
    {
        return mtlrenderpipelinedescriptor_raster_sample_count(handle);
    }

    public static function setRasterSampleCount(int handle, int rasterSampleCount) -> void
    {
        mtlrenderpipelinedescriptor_set_raster_sample_count(handle, rasterSampleCount);
    }

    public static function colorAttachments(int handle) -> int
    {
        return mtlrenderpipelinedescriptor_color_attachments(handle);
    }

    public static function label(int handle) -> var
    {
        var result;

        let result = mtlrenderpipelinedescriptor_label(handle);

        return result;
    }

    public static function setLabel(int handle, var label) -> void
    {
        mtlrenderpipelinedescriptor_set_label(handle, label);
    }

    public static function depthAttachmentPixelFormat(int handle) -> int
    {
        return mtlrenderpipelinedescriptor_depth_attachment_pixel_format(handle);
    }

    public static function setDepthAttachmentPixelFormat(int handle, int depthAttachmentPixelFormat) -> void
    {
        mtlrenderpipelinedescriptor_set_depth_attachment_pixel_format(handle, depthAttachmentPixelFormat);
    }

    public static function stencilAttachmentPixelFormat(int handle) -> int
    {
        return mtlrenderpipelinedescriptor_stencil_attachment_pixel_format(handle);
    }

    public static function setStencilAttachmentPixelFormat(int handle, int stencilAttachmentPixelFormat) -> void
    {
        mtlrenderpipelinedescriptor_set_stencil_attachment_pixel_format(handle, stencilAttachmentPixelFormat);
    }
}
