
extern zend_class_entry *metal_mtl_mtlrenderpipelinecolorattachmentdescriptorarray_mtlrenderpipelinecolorattachmentdescriptorarray_ce;

ZEPHIR_INIT_CLASS(Metal_MTL_MTLRenderPipelineColorAttachmentDescriptorArray_MTLRenderPipelineColorAttachmentDescriptorArray);

PHP_METHOD(Metal_MTL_MTLRenderPipelineColorAttachmentDescriptorArray_MTLRenderPipelineColorAttachmentDescriptorArray, objectAtIndexedSubscript);
PHP_METHOD(Metal_MTL_MTLRenderPipelineColorAttachmentDescriptorArray_MTLRenderPipelineColorAttachmentDescriptorArray, setObjectAtIndexedSubscript);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_metal_mtl_mtlrenderpipelinecolorattachmentdescriptorarray_mtlrenderpipelinecolorattachmentdescriptorarray_objectatindexedsubscript, 0, 2, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, attachmentIndex, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_metal_mtl_mtlrenderpipelinecolorattachmentdescriptorarray_mtlrenderpipelinecolorattachmentdescriptorarray_setobjectatindexedsubscript, 0, 3, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, attachment, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, attachmentIndex, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(metal_mtl_mtlrenderpipelinecolorattachmentdescriptorarray_mtlrenderpipelinecolorattachmentdescriptorarray_method_entry) {
	PHP_ME(Metal_MTL_MTLRenderPipelineColorAttachmentDescriptorArray_MTLRenderPipelineColorAttachmentDescriptorArray, objectAtIndexedSubscript, arginfo_metal_mtl_mtlrenderpipelinecolorattachmentdescriptorarray_mtlrenderpipelinecolorattachmentdescriptorarray_objectatindexedsubscript, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Metal_MTL_MTLRenderPipelineColorAttachmentDescriptorArray_MTLRenderPipelineColorAttachmentDescriptorArray, setObjectAtIndexedSubscript, arginfo_metal_mtl_mtlrenderpipelinecolorattachmentdescriptorarray_mtlrenderpipelinecolorattachmentdescriptorarray_setobjectatindexedsubscript, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
