// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Metal\MTL\MTLDevice;

class MTLDevice
{
    public static function createSystemDefault() -> int
    {
        return mtldevice_create_system_default();
    }

    public static function name(int handle) -> var
    {
        var result;

        let result = mtldevice_name(handle);

        return result;
    }

    public static function newCommandQueue(int handle) -> int
    {
        return mtldevice_new_command_queue(handle);
    }

    public static function newTextureWithDescriptor(int handle, int descriptor) -> int
    {
        return mtldevice_new_texture_with_descriptor(handle, descriptor);
    }

    public static function newBufferWithLengthOptions(int handle, int length, int options) -> int
    {
        return mtldevice_new_buffer_with_length_options(handle, length, options);
    }

    public static function newBufferWithBytesLengthOptions(int handle, string bytes, int options) -> int
    {
        return mtldevice_new_buffer_with_bytes_length_options(handle, bytes, options);
    }

    public static function newLibraryWithSourceOptionsError(int handle, string source, int options) -> array
    {
        var result;

        let result = mtldevice_new_library_with_source_options_error(handle, source, options);

        return result;
    }

    public static function newRenderPipelineStateWithDescriptorError(int handle, int descriptor) -> array
    {
        var result;

        let result = mtldevice_new_render_pipeline_state_with_descriptor_error(handle, descriptor);

        return result;
    }

    public static function newComputePipelineStateWithFunctionError(int handle, int computeFunction) -> array
    {
        var result;

        let result = mtldevice_new_compute_pipeline_state_with_function_error(handle, computeFunction);

        return result;
    }

    public static function newDepthStencilStateWithDescriptor(int handle, int descriptor) -> int
    {
        return mtldevice_new_depth_stencil_state_with_descriptor(handle, descriptor);
    }

    public static function newSamplerStateWithDescriptor(int handle, int descriptor) -> int
    {
        return mtldevice_new_sampler_state_with_descriptor(handle, descriptor);
    }
}
