// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Metal\MTL\MTLRenderPassColorAttachmentDescriptor;

class MTLRenderPassColorAttachmentDescriptor
{
    public static function clearColor(int handle) -> array
    {
        var result;

        let result = mtlrenderpasscolorattachmentdescriptor_clear_color(handle);

        return result;
    }

    public static function setClearColor(int handle, double red, double green, double blue, double alpha) -> void
    {
        mtlrenderpasscolorattachmentdescriptor_set_clear_color(handle, red, green, blue, alpha);
    }
}
