// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Metal\MTL\MTLTexture;

class MTLTexture
{
    public static function width(int handle) -> int
    {
        return mtltexture_width(handle);
    }

    public static function height(int handle) -> int
    {
        return mtltexture_height(handle);
    }

    public static function pixelFormat(int handle) -> int
    {
        return mtltexture_pixel_format(handle);
    }

    public static function getBytesBytesPerRowFromRegionMipmapLevel(int handle, int bytesPerRow, int x, int y, int z, int width, int height, int depth, int mipmapLevel) -> string
    {
        var result;

        let result = mtltexture_get_bytes_bytes_per_row_from_region_mipmap_level(handle, bytesPerRow, x, y, z, width, height, depth, mipmapLevel);

        return result;
    }

    public static function replaceRegionMipmapLevelWithBytesBytesPerRow(int handle, int x, int y, int z, int width, int height, int depth, int mipmapLevel, string bytes, int bytesPerRow) -> bool
    {
        int r;

        let r = mtltexture_replace_region_mipmap_level_with_bytes_bytes_per_row(handle, x, y, z, width, height, depth, mipmapLevel, bytes, bytesPerRow);

        return r == 1;
    }
}
