// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Metal\MTL\MTLRenderPassStencilAttachmentDescriptor;

class MTLRenderPassStencilAttachmentDescriptor
{
    public static function clearStencil(int handle) -> int
    {
        return mtlrenderpassstencilattachmentdescriptor_clear_stencil(handle);
    }

    public static function setClearStencil(int handle, int clearStencil) -> void
    {
        mtlrenderpassstencilattachmentdescriptor_set_clear_stencil(handle, clearStencil);
    }
}
