// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Metal\MTL\MTLVertexAttributeDescriptorArray;

class MTLVertexAttributeDescriptorArray
{
    public static function objectAtIndexedSubscript(int handle, int index) -> int
    {
        return mtlvertexattributedescriptorarray_object_at_indexed_subscript(handle, index);
    }

    public static function setObjectAtIndexedSubscript(int handle, int attributeDesc, int index) -> void
    {
        mtlvertexattributedescriptorarray_set_object_at_indexed_subscript(handle, attributeDesc, index);
    }
}
