// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Metal\MTL\MTLTextureDescriptor;

class MTLTextureDescriptor
{
    public static function texture2DDescriptorWithPixelFormatWidthHeightMipmapped(int pixelFormat, int width, int height, bool mipmapped) -> int
    {
        return mtltexturedescriptor_texture2d_descriptor_with_pixel_format_width_height_mipmapped(pixelFormat, width, height, mipmapped);
    }

    public static function usage(int handle) -> int
    {
        return mtltexturedescriptor_usage(handle);
    }

    public static function setUsage(int handle, int usage) -> void
    {
        mtltexturedescriptor_set_usage(handle, usage);
    }

    public static function storageMode(int handle) -> int
    {
        return mtltexturedescriptor_storage_mode(handle);
    }

    public static function setStorageMode(int handle, int storageMode) -> void
    {
        mtltexturedescriptor_set_storage_mode(handle, storageMode);
    }
}
