
extern zend_class_entry *metal_mtl_mtlrenderpassattachmentdescriptor_mtlrenderpassattachmentdescriptor_ce;

ZEPHIR_INIT_CLASS(Metal_MTL_MTLRenderPassAttachmentDescriptor_MTLRenderPassAttachmentDescriptor);

PHP_METHOD(Metal_MTL_MTLRenderPassAttachmentDescriptor_MTLRenderPassAttachmentDescriptor, texture);
PHP_METHOD(Metal_MTL_MTLRenderPassAttachmentDescriptor_MTLRenderPassAttachmentDescriptor, setTexture);
PHP_METHOD(Metal_MTL_MTLRenderPassAttachmentDescriptor_MTLRenderPassAttachmentDescriptor, loadAction);
PHP_METHOD(Metal_MTL_MTLRenderPassAttachmentDescriptor_MTLRenderPassAttachmentDescriptor, setLoadAction);
PHP_METHOD(Metal_MTL_MTLRenderPassAttachmentDescriptor_MTLRenderPassAttachmentDescriptor, storeAction);
PHP_METHOD(Metal_MTL_MTLRenderPassAttachmentDescriptor_MTLRenderPassAttachmentDescriptor, setStoreAction);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_metal_mtl_mtlrenderpassattachmentdescriptor_mtlrenderpassattachmentdescriptor_texture, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_metal_mtl_mtlrenderpassattachmentdescriptor_mtlrenderpassattachmentdescriptor_settexture, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, texture, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_metal_mtl_mtlrenderpassattachmentdescriptor_mtlrenderpassattachmentdescriptor_loadaction, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_metal_mtl_mtlrenderpassattachmentdescriptor_mtlrenderpassattachmentdescriptor_setloadaction, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, loadAction, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_metal_mtl_mtlrenderpassattachmentdescriptor_mtlrenderpassattachmentdescriptor_storeaction, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_metal_mtl_mtlrenderpassattachmentdescriptor_mtlrenderpassattachmentdescriptor_setstoreaction, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, storeAction, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(metal_mtl_mtlrenderpassattachmentdescriptor_mtlrenderpassattachmentdescriptor_method_entry) {
	PHP_ME(Metal_MTL_MTLRenderPassAttachmentDescriptor_MTLRenderPassAttachmentDescriptor, texture, arginfo_metal_mtl_mtlrenderpassattachmentdescriptor_mtlrenderpassattachmentdescriptor_texture, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Metal_MTL_MTLRenderPassAttachmentDescriptor_MTLRenderPassAttachmentDescriptor, setTexture, arginfo_metal_mtl_mtlrenderpassattachmentdescriptor_mtlrenderpassattachmentdescriptor_settexture, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Metal_MTL_MTLRenderPassAttachmentDescriptor_MTLRenderPassAttachmentDescriptor, loadAction, arginfo_metal_mtl_mtlrenderpassattachmentdescriptor_mtlrenderpassattachmentdescriptor_loadaction, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Metal_MTL_MTLRenderPassAttachmentDescriptor_MTLRenderPassAttachmentDescriptor, setLoadAction, arginfo_metal_mtl_mtlrenderpassattachmentdescriptor_mtlrenderpassattachmentdescriptor_setloadaction, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Metal_MTL_MTLRenderPassAttachmentDescriptor_MTLRenderPassAttachmentDescriptor, storeAction, arginfo_metal_mtl_mtlrenderpassattachmentdescriptor_mtlrenderpassattachmentdescriptor_storeaction, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Metal_MTL_MTLRenderPassAttachmentDescriptor_MTLRenderPassAttachmentDescriptor, setStoreAction, arginfo_metal_mtl_mtlrenderpassattachmentdescriptor_mtlrenderpassattachmentdescriptor_setstoreaction, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
