// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Metal\Bridge;

class Bridge
{
    public static function retain(int handle) -> bool
    {
        int r;

        let r = bridge_retain(handle);

        return r == 1;
    }

    public static function release(int handle) -> void
    {
        bridge_release(handle);
    }

    public static function isValid(int handle) -> bool
    {
        int r;

        let r = bridge_is_valid(handle);

        return r == 1;
    }

    public static function className(int handle) -> var
    {
        var result;

        let result = bridge_class_name(handle);

        return result;
    }

    public static function pointerOf(int handle) -> int
    {
        return bridge_pointer_of(handle);
    }

    public static function adopt(string className, int pointerBits) -> int
    {
        return bridge_adopt(className, pointerBits);
    }

    public static function errorDescription(int handle) -> var
    {
        var result;

        let result = bridge_error_description(handle);

        return result;
    }
}
