// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Metal\MTL\MTLVertexBufferLayoutDescriptor;

class MTLVertexBufferLayoutDescriptor
{
    public static function stride(int handle) -> int
    {
        return mtlvertexbufferlayoutdescriptor_stride(handle);
    }

    public static function setStride(int handle, int stride) -> void
    {
        mtlvertexbufferlayoutdescriptor_set_stride(handle, stride);
    }

    public static function stepFunction(int handle) -> int
    {
        return mtlvertexbufferlayoutdescriptor_step_function(handle);
    }

    public static function setStepFunction(int handle, int stepFunction) -> void
    {
        mtlvertexbufferlayoutdescriptor_set_step_function(handle, stepFunction);
    }

    public static function stepRate(int handle) -> int
    {
        return mtlvertexbufferlayoutdescriptor_step_rate(handle);
    }

    public static function setStepRate(int handle, int stepRate) -> void
    {
        mtlvertexbufferlayoutdescriptor_set_step_rate(handle, stepRate);
    }
}
