// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Metal\MTL\MTLRenderPassColorAttachmentDescriptorArray;

class MTLRenderPassColorAttachmentDescriptorArray
{
    public static function objectAtIndexedSubscript(int handle, int attachmentIndex) -> int
    {
        return mtlrenderpasscolorattachmentdescriptorarray_object_at_indexed_subscript(handle, attachmentIndex);
    }

    public static function setObjectAtIndexedSubscript(int handle, int attachment, int attachmentIndex) -> void
    {
        mtlrenderpasscolorattachmentdescriptorarray_set_object_at_indexed_subscript(handle, attachment, attachmentIndex);
    }
}
