// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Metal\MTL\MTLDepthStencilState;

class MTLDepthStencilState
{
    public static function label(int handle) -> var
    {
        var result;

        let result = mtldepthstencilstate_label(handle);

        return result;
    }
}
