
extern zend_class_entry *metal_mtl_mtlrenderpassstencilattachmentdescriptor_mtlrenderpassstencilattachmentdescriptor_ce;

ZEPHIR_INIT_CLASS(Metal_MTL_MTLRenderPassStencilAttachmentDescriptor_MTLRenderPassStencilAttachmentDescriptor);

PHP_METHOD(Metal_MTL_MTLRenderPassStencilAttachmentDescriptor_MTLRenderPassStencilAttachmentDescriptor, clearStencil);
PHP_METHOD(Metal_MTL_MTLRenderPassStencilAttachmentDescriptor_MTLRenderPassStencilAttachmentDescriptor, setClearStencil);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_metal_mtl_mtlrenderpassstencilattachmentdescriptor_mtlrenderpassstencilattachmentdescriptor_clearstencil, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_metal_mtl_mtlrenderpassstencilattachmentdescriptor_mtlrenderpassstencilattachmentdescriptor_setclearstencil, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, clearStencil, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(metal_mtl_mtlrenderpassstencilattachmentdescriptor_mtlrenderpassstencilattachmentdescriptor_method_entry) {
	PHP_ME(Metal_MTL_MTLRenderPassStencilAttachmentDescriptor_MTLRenderPassStencilAttachmentDescriptor, clearStencil, arginfo_metal_mtl_mtlrenderpassstencilattachmentdescriptor_mtlrenderpassstencilattachmentdescriptor_clearstencil, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Metal_MTL_MTLRenderPassStencilAttachmentDescriptor_MTLRenderPassStencilAttachmentDescriptor, setClearStencil, arginfo_metal_mtl_mtlrenderpassstencilattachmentdescriptor_mtlrenderpassstencilattachmentdescriptor_setclearstencil, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
