// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Metal\MTL\MTLRenderPipelineColorAttachmentDescriptor;

class MTLRenderPipelineColorAttachmentDescriptor
{
    public static function pixelFormat(int handle) -> int
    {
        return mtlrenderpipelinecolorattachmentdescriptor_pixel_format(handle);
    }

    public static function setPixelFormat(int handle, int pixelFormat) -> void
    {
        mtlrenderpipelinecolorattachmentdescriptor_set_pixel_format(handle, pixelFormat);
    }

    public static function blendingEnabled(int handle) -> bool
    {
        int r;

        let r = mtlrenderpipelinecolorattachmentdescriptor_blending_enabled(handle);

        return r == 1;
    }

    public static function setBlendingEnabled(int handle, bool blendingEnabled) -> void
    {
        mtlrenderpipelinecolorattachmentdescriptor_set_blending_enabled(handle, blendingEnabled);
    }
}
