// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Metal\MTL\MTLVertexDescriptor;

class MTLVertexDescriptor
{
    public static function vertexDescriptor() -> int
    {
        return mtlvertexdescriptor_vertex_descriptor();
    }

    public static function attributes(int handle) -> int
    {
        return mtlvertexdescriptor_attributes(handle);
    }

    public static function layouts(int handle) -> int
    {
        return mtlvertexdescriptor_layouts(handle);
    }
}
