// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Metal\MTL\MTLRenderPassDescriptor;

class MTLRenderPassDescriptor
{
    public static function renderPassDescriptor() -> int
    {
        return mtlrenderpassdescriptor_render_pass_descriptor();
    }

    public static function colorAttachments(int handle) -> int
    {
        return mtlrenderpassdescriptor_color_attachments(handle);
    }

    public static function depthAttachment(int handle) -> int
    {
        return mtlrenderpassdescriptor_depth_attachment(handle);
    }

    public static function setDepthAttachment(int handle, int depthAttachment) -> void
    {
        mtlrenderpassdescriptor_set_depth_attachment(handle, depthAttachment);
    }

    public static function stencilAttachment(int handle) -> int
    {
        return mtlrenderpassdescriptor_stencil_attachment(handle);
    }

    public static function setStencilAttachment(int handle, int stencilAttachment) -> void
    {
        mtlrenderpassdescriptor_set_stencil_attachment(handle, stencilAttachment);
    }
}
