// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Metal\MTL\MTLRenderPassDescriptor;

class MTLRenderPassDescriptor
{
    public static function renderPassDescriptor() -> int
    {
        return mtlrenderpassdescriptor_render_pass_descriptor();
    }

    public static function colorAttachments(int handle) -> int
    {
        return mtlrenderpassdescriptor_color_attachments(handle);
    }
}
