// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Metal\MTL\MTLVertexBufferLayoutDescriptorArray;

class MTLVertexBufferLayoutDescriptorArray
{
    public static function objectAtIndexedSubscript(int handle, int index) -> int
    {
        return mtlvertexbufferlayoutdescriptorarray_object_at_indexed_subscript(handle, index);
    }

    public static function setObjectAtIndexedSubscript(int handle, int bufferDesc, int index) -> void
    {
        mtlvertexbufferlayoutdescriptorarray_set_object_at_indexed_subscript(handle, bufferDesc, index);
    }
}
