// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Metal\QuartzCore\CAMetalDrawable;

class CAMetalDrawable
{
    public static function texture(int handle) -> int
    {
        return cametaldrawable_texture(handle);
    }

    public static function layer(int handle) -> int
    {
        return cametaldrawable_layer(handle);
    }
}
