// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Metal\MTL\MTLBlitCommandEncoder;

class MTLBlitCommandEncoder
{
    public static function copyFromBufferSourceOffsetToBufferDestinationOffsetSize(int handle, int sourceBuffer, int sourceOffset, int destinationBuffer, int destinationOffset, int size) -> void
    {
        mtlblitcommandencoder_copy_from_buffer_source_offset_to_buffer_destination_offset_size(handle, sourceBuffer, sourceOffset, destinationBuffer, destinationOffset, size);
    }

    public static function fillBufferRangeValue(int handle, int buffer, int rangeLocation, int rangeLength, int value) -> void
    {
        mtlblitcommandencoder_fill_buffer_range_value(handle, buffer, rangeLocation, rangeLength, value);
    }

    public static function copyFromBufferSourceOffsetSourceBytesPerRowSourceBytesPerImageSourceSizeToTextureDestinationSliceDestinationLevelDestinationOrigin(int handle, int sourceBuffer, int sourceOffset, int sourceBytesPerRow, int sourceBytesPerImage, int sourceSizeWidth, int sourceSizeHeight, int sourceSizeDepth, int destinationTexture, int destinationSlice, int destinationLevel, int destinationOriginX, int destinationOriginY, int destinationOriginZ) -> void
    {
        mtlblitcommandencoder_copy_from_buffer_source_offset_source_bytes_per_row_source_bytes_per_image_source_size_to_texture_destination_slice_destination_level_destination_origin(handle, sourceBuffer, sourceOffset, sourceBytesPerRow, sourceBytesPerImage, sourceSizeWidth, sourceSizeHeight, sourceSizeDepth, destinationTexture, destinationSlice, destinationLevel, destinationOriginX, destinationOriginY, destinationOriginZ);
    }

    public static function copyFromTextureSourceSliceSourceLevelSourceOriginSourceSizeToBufferDestinationOffsetDestinationBytesPerRowDestinationBytesPerImage(int handle, int sourceTexture, int sourceSlice, int sourceLevel, int sourceOriginX, int sourceOriginY, int sourceOriginZ, int sourceSizeWidth, int sourceSizeHeight, int sourceSizeDepth, int destinationBuffer, int destinationOffset, int destinationBytesPerRow, int destinationBytesPerImage) -> void
    {
        mtlblitcommandencoder_copy_from_texture_source_slice_source_level_source_origin_source_size_to_buffer_destination_offset_destination_bytes_per_row_destination_bytes_per_image(handle, sourceTexture, sourceSlice, sourceLevel, sourceOriginX, sourceOriginY, sourceOriginZ, sourceSizeWidth, sourceSizeHeight, sourceSizeDepth, destinationBuffer, destinationOffset, destinationBytesPerRow, destinationBytesPerImage);
    }

    public static function generateMipmapsForTexture(int handle, int texture) -> void
    {
        mtlblitcommandencoder_generate_mipmaps_for_texture(handle, texture);
    }

    public static function synchronizeResource(int handle, int resource_) -> void
    {
        mtlblitcommandencoder_synchronize_resource(handle, resource_);
    }
}
