// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Metal\MTL\MTLComputeCommandEncoder;

class MTLComputeCommandEncoder
{
    public static function setComputePipelineState(int handle, int state) -> void
    {
        mtlcomputecommandencoder_set_compute_pipeline_state(handle, state);
    }

    public static function setBufferOffsetAtIndex(int handle, int buffer, int offset, int index) -> void
    {
        mtlcomputecommandencoder_set_buffer_offset_at_index(handle, buffer, offset, index);
    }

    public static function setTextureAtIndex(int handle, int texture, int index) -> void
    {
        mtlcomputecommandencoder_set_texture_at_index(handle, texture, index);
    }

    public static function dispatchThreadgroupsThreadsPerThreadgroup(int handle, int threadgroupsPerGridWidth, int threadgroupsPerGridHeight, int threadgroupsPerGridDepth, int threadsPerThreadgroupWidth, int threadsPerThreadgroupHeight, int threadsPerThreadgroupDepth) -> void
    {
        mtlcomputecommandencoder_dispatch_threadgroups_threads_per_threadgroup(handle, threadgroupsPerGridWidth, threadgroupsPerGridHeight, threadgroupsPerGridDepth, threadsPerThreadgroupWidth, threadsPerThreadgroupHeight, threadsPerThreadgroupDepth);
    }

    public static function dispatchThreadsThreadsPerThreadgroup(int handle, int threadsPerGridWidth, int threadsPerGridHeight, int threadsPerGridDepth, int threadsPerThreadgroupWidth, int threadsPerThreadgroupHeight, int threadsPerThreadgroupDepth) -> void
    {
        mtlcomputecommandencoder_dispatch_threads_threads_per_threadgroup(handle, threadsPerGridWidth, threadsPerGridHeight, threadsPerGridDepth, threadsPerThreadgroupWidth, threadsPerThreadgroupHeight, threadsPerThreadgroupDepth);
    }
}
