
extern zend_class_entry *metal_mtl_mtlrenderpipelinedescriptor_mtlrenderpipelinedescriptor_ce;

ZEPHIR_INIT_CLASS(Metal_MTL_MTLRenderPipelineDescriptor_MTLRenderPipelineDescriptor);

PHP_METHOD(Metal_MTL_MTLRenderPipelineDescriptor_MTLRenderPipelineDescriptor, init);
PHP_METHOD(Metal_MTL_MTLRenderPipelineDescriptor_MTLRenderPipelineDescriptor, vertexFunction);
PHP_METHOD(Metal_MTL_MTLRenderPipelineDescriptor_MTLRenderPipelineDescriptor, setVertexFunction);
PHP_METHOD(Metal_MTL_MTLRenderPipelineDescriptor_MTLRenderPipelineDescriptor, fragmentFunction);
PHP_METHOD(Metal_MTL_MTLRenderPipelineDescriptor_MTLRenderPipelineDescriptor, setFragmentFunction);
PHP_METHOD(Metal_MTL_MTLRenderPipelineDescriptor_MTLRenderPipelineDescriptor, vertexDescriptor);
PHP_METHOD(Metal_MTL_MTLRenderPipelineDescriptor_MTLRenderPipelineDescriptor, setVertexDescriptor);
PHP_METHOD(Metal_MTL_MTLRenderPipelineDescriptor_MTLRenderPipelineDescriptor, rasterSampleCount);
PHP_METHOD(Metal_MTL_MTLRenderPipelineDescriptor_MTLRenderPipelineDescriptor, setRasterSampleCount);
PHP_METHOD(Metal_MTL_MTLRenderPipelineDescriptor_MTLRenderPipelineDescriptor, colorAttachments);
PHP_METHOD(Metal_MTL_MTLRenderPipelineDescriptor_MTLRenderPipelineDescriptor, label);
PHP_METHOD(Metal_MTL_MTLRenderPipelineDescriptor_MTLRenderPipelineDescriptor, setLabel);
PHP_METHOD(Metal_MTL_MTLRenderPipelineDescriptor_MTLRenderPipelineDescriptor, depthAttachmentPixelFormat);
PHP_METHOD(Metal_MTL_MTLRenderPipelineDescriptor_MTLRenderPipelineDescriptor, setDepthAttachmentPixelFormat);
PHP_METHOD(Metal_MTL_MTLRenderPipelineDescriptor_MTLRenderPipelineDescriptor, stencilAttachmentPixelFormat);
PHP_METHOD(Metal_MTL_MTLRenderPipelineDescriptor_MTLRenderPipelineDescriptor, setStencilAttachmentPixelFormat);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_metal_mtl_mtlrenderpipelinedescriptor_mtlrenderpipelinedescriptor_init, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_metal_mtl_mtlrenderpipelinedescriptor_mtlrenderpipelinedescriptor_vertexfunction, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_metal_mtl_mtlrenderpipelinedescriptor_mtlrenderpipelinedescriptor_setvertexfunction, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, vertexFunction, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_metal_mtl_mtlrenderpipelinedescriptor_mtlrenderpipelinedescriptor_fragmentfunction, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_metal_mtl_mtlrenderpipelinedescriptor_mtlrenderpipelinedescriptor_setfragmentfunction, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, fragmentFunction, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_metal_mtl_mtlrenderpipelinedescriptor_mtlrenderpipelinedescriptor_vertexdescriptor, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_metal_mtl_mtlrenderpipelinedescriptor_mtlrenderpipelinedescriptor_setvertexdescriptor, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, vertexDescriptor, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_metal_mtl_mtlrenderpipelinedescriptor_mtlrenderpipelinedescriptor_rastersamplecount, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_metal_mtl_mtlrenderpipelinedescriptor_mtlrenderpipelinedescriptor_setrastersamplecount, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, rasterSampleCount, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_metal_mtl_mtlrenderpipelinedescriptor_mtlrenderpipelinedescriptor_colorattachments, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_metal_mtl_mtlrenderpipelinedescriptor_mtlrenderpipelinedescriptor_label, 0, 0, 1)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_metal_mtl_mtlrenderpipelinedescriptor_mtlrenderpipelinedescriptor_setlabel, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_INFO(0, label)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_metal_mtl_mtlrenderpipelinedescriptor_mtlrenderpipelinedescriptor_depthattachmentpixelformat, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_metal_mtl_mtlrenderpipelinedescriptor_mtlrenderpipelinedescriptor_setdepthattachmentpixelformat, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, depthAttachmentPixelFormat, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_metal_mtl_mtlrenderpipelinedescriptor_mtlrenderpipelinedescriptor_stencilattachmentpixelformat, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_metal_mtl_mtlrenderpipelinedescriptor_mtlrenderpipelinedescriptor_setstencilattachmentpixelformat, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, stencilAttachmentPixelFormat, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(metal_mtl_mtlrenderpipelinedescriptor_mtlrenderpipelinedescriptor_method_entry) {
	PHP_ME(Metal_MTL_MTLRenderPipelineDescriptor_MTLRenderPipelineDescriptor, init, arginfo_metal_mtl_mtlrenderpipelinedescriptor_mtlrenderpipelinedescriptor_init, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Metal_MTL_MTLRenderPipelineDescriptor_MTLRenderPipelineDescriptor, vertexFunction, arginfo_metal_mtl_mtlrenderpipelinedescriptor_mtlrenderpipelinedescriptor_vertexfunction, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Metal_MTL_MTLRenderPipelineDescriptor_MTLRenderPipelineDescriptor, setVertexFunction, arginfo_metal_mtl_mtlrenderpipelinedescriptor_mtlrenderpipelinedescriptor_setvertexfunction, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Metal_MTL_MTLRenderPipelineDescriptor_MTLRenderPipelineDescriptor, fragmentFunction, arginfo_metal_mtl_mtlrenderpipelinedescriptor_mtlrenderpipelinedescriptor_fragmentfunction, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Metal_MTL_MTLRenderPipelineDescriptor_MTLRenderPipelineDescriptor, setFragmentFunction, arginfo_metal_mtl_mtlrenderpipelinedescriptor_mtlrenderpipelinedescriptor_setfragmentfunction, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Metal_MTL_MTLRenderPipelineDescriptor_MTLRenderPipelineDescriptor, vertexDescriptor, arginfo_metal_mtl_mtlrenderpipelinedescriptor_mtlrenderpipelinedescriptor_vertexdescriptor, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Metal_MTL_MTLRenderPipelineDescriptor_MTLRenderPipelineDescriptor, setVertexDescriptor, arginfo_metal_mtl_mtlrenderpipelinedescriptor_mtlrenderpipelinedescriptor_setvertexdescriptor, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Metal_MTL_MTLRenderPipelineDescriptor_MTLRenderPipelineDescriptor, rasterSampleCount, arginfo_metal_mtl_mtlrenderpipelinedescriptor_mtlrenderpipelinedescriptor_rastersamplecount, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Metal_MTL_MTLRenderPipelineDescriptor_MTLRenderPipelineDescriptor, setRasterSampleCount, arginfo_metal_mtl_mtlrenderpipelinedescriptor_mtlrenderpipelinedescriptor_setrastersamplecount, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Metal_MTL_MTLRenderPipelineDescriptor_MTLRenderPipelineDescriptor, colorAttachments, arginfo_metal_mtl_mtlrenderpipelinedescriptor_mtlrenderpipelinedescriptor_colorattachments, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Metal_MTL_MTLRenderPipelineDescriptor_MTLRenderPipelineDescriptor, label, arginfo_metal_mtl_mtlrenderpipelinedescriptor_mtlrenderpipelinedescriptor_label, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Metal_MTL_MTLRenderPipelineDescriptor_MTLRenderPipelineDescriptor, setLabel, arginfo_metal_mtl_mtlrenderpipelinedescriptor_mtlrenderpipelinedescriptor_setlabel, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Metal_MTL_MTLRenderPipelineDescriptor_MTLRenderPipelineDescriptor, depthAttachmentPixelFormat, arginfo_metal_mtl_mtlrenderpipelinedescriptor_mtlrenderpipelinedescriptor_depthattachmentpixelformat, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Metal_MTL_MTLRenderPipelineDescriptor_MTLRenderPipelineDescriptor, setDepthAttachmentPixelFormat, arginfo_metal_mtl_mtlrenderpipelinedescriptor_mtlrenderpipelinedescriptor_setdepthattachmentpixelformat, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Metal_MTL_MTLRenderPipelineDescriptor_MTLRenderPipelineDescriptor, stencilAttachmentPixelFormat, arginfo_metal_mtl_mtlrenderpipelinedescriptor_mtlrenderpipelinedescriptor_stencilattachmentpixelformat, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Metal_MTL_MTLRenderPipelineDescriptor_MTLRenderPipelineDescriptor, setStencilAttachmentPixelFormat, arginfo_metal_mtl_mtlrenderpipelinedescriptor_mtlrenderpipelinedescriptor_setstencilattachmentpixelformat, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
