<?php

/* GENERATED by scripts/gen-zep.php — DO NOT EDIT. */

namespace Zephir\Optimizers\FunctionCall;

use Zephir\Call;
use Zephir\CompilationContext;
use Zephir\CompiledExpression;
use Zephir\Exception\CompilerException;
use Zephir\Optimizers\OptimizerAbstract;

class MtlblitcommandencoderFillBufferRangeValueOptimizer extends OptimizerAbstract
{
    public function optimize(array $expression, Call $call, CompilationContext $context)
    {
        if (!isset($expression['parameters']) || count($expression['parameters']) !== 5) {
            throw new CompilerException("'mtlblitcommandencoder_fill_buffer_range_value' requires exactly 5 parameters", $expression);
        }

        $context->headersManager->add('src/mtl-blitcommandencoder');

        $resolvedParams = $call->getReadOnlyResolvedParams($expression['parameters'], $context, $expression);

        $context->codePrinter->output('mtl_mtlblitcommandencoder_fill_buffer_range_value(' . $resolvedParams[0] . ', ' . $resolvedParams[1] . ', ' . $resolvedParams[2] . ', ' . $resolvedParams[3] . ', ' . $resolvedParams[4] . ');');

        return new CompiledExpression('null', 'null', $expression);
    }
}
