<?php

/* GENERATED by scripts/gen-zep.php — DO NOT EDIT. */

namespace Zephir\Optimizers\FunctionCall;

use Zephir\Call;
use Zephir\CompilationContext;
use Zephir\CompiledExpression;
use Zephir\Exception\CompilerException;
use Zephir\Optimizers\OptimizerAbstract;

class MtlblitcommandencoderCopyFromTextureSourceSliceSourceLevelSourceOriginSourceSizeToBufferDestinationOffsetDestinationBytesPerRowDestinationBytesPerImageOptimizer extends OptimizerAbstract
{
    public function optimize(array $expression, Call $call, CompilationContext $context)
    {
        if (!isset($expression['parameters']) || count($expression['parameters']) !== 14) {
            throw new CompilerException("'mtlblitcommandencoder_copy_from_texture_source_slice_source_level_source_origin_source_size_to_buffer_destination_offset_destination_bytes_per_row_destination_bytes_per_image' requires exactly 14 parameters", $expression);
        }

        $context->headersManager->add('src/mtl-blitcommandencoder');

        $resolvedParams = $call->getReadOnlyResolvedParams($expression['parameters'], $context, $expression);

        $context->codePrinter->output('mtl_mtlblitcommandencoder_copy_from_texture_source_slice_source_level_source_origin_source_size_to_buffer_destination_offset_destination_bytes_per_row_destination_bytes_per_image(' . $resolvedParams[0] . ', ' . $resolvedParams[1] . ', ' . $resolvedParams[2] . ', ' . $resolvedParams[3] . ', ' . $resolvedParams[4] . ', ' . $resolvedParams[5] . ', ' . $resolvedParams[6] . ', ' . $resolvedParams[7] . ', ' . $resolvedParams[8] . ', ' . $resolvedParams[9] . ', ' . $resolvedParams[10] . ', ' . $resolvedParams[11] . ', ' . $resolvedParams[12] . ', ' . $resolvedParams[13] . ');');

        return new CompiledExpression('null', 'null', $expression);
    }
}
