<?php

/* GENERATED by scripts/gen-zep.php — DO NOT EDIT. */

namespace Zephir\Optimizers\FunctionCall;

use Zephir\Call;
use Zephir\CompilationContext;
use Zephir\CompiledExpression;
use Zephir\Exception\CompilerException;
use Zephir\Optimizers\OptimizerAbstract;

class MtlrendercommandencoderDrawIndexedPrimitivesIndexCountIndexTypeIndexBufferIndexBufferOffsetOptimizer extends OptimizerAbstract
{
    public function optimize(array $expression, Call $call, CompilationContext $context)
    {
        if (!isset($expression['parameters']) || count($expression['parameters']) !== 6) {
            throw new CompilerException("'mtlrendercommandencoder_draw_indexed_primitives_index_count_index_type_index_buffer_index_buffer_offset' requires exactly 6 parameters", $expression);
        }

        $context->headersManager->add('src/mtl-rendercommandencoder');

        $resolvedParams = $call->getReadOnlyResolvedParams($expression['parameters'], $context, $expression);

        $context->codePrinter->output('mtl_mtlrendercommandencoder_draw_indexed_primitives_index_count_index_type_index_buffer_index_buffer_offset(' . $resolvedParams[0] . ', ' . $resolvedParams[1] . ', ' . $resolvedParams[2] . ', ' . $resolvedParams[3] . ', ' . $resolvedParams[4] . ', ' . $resolvedParams[5] . ');');

        return new CompiledExpression('null', 'null', $expression);
    }
}
