<?php

/* GENERATED by scripts/gen-zep.php — DO NOT EDIT. */

namespace Zephir\Optimizers\FunctionCall;

use Zephir\Call;
use Zephir\CompilationContext;
use Zephir\CompiledExpression;
use Zephir\Exception\CompilerException;
use Zephir\Optimizers\OptimizerAbstract;

class MtlrendercommandencoderSetFragmentBufferOffsetAtIndexOptimizer extends OptimizerAbstract
{
    public function optimize(array $expression, Call $call, CompilationContext $context)
    {
        if (!isset($expression['parameters']) || count($expression['parameters']) !== 4) {
            throw new CompilerException("'mtlrendercommandencoder_set_fragment_buffer_offset_at_index' requires exactly 4 parameters", $expression);
        }

        $context->headersManager->add('src/mtl-rendercommandencoder');

        $resolvedParams = $call->getReadOnlyResolvedParams($expression['parameters'], $context, $expression);

        $context->codePrinter->output('mtl_mtlrendercommandencoder_set_fragment_buffer_offset_at_index(' . $resolvedParams[0] . ', ' . $resolvedParams[1] . ', ' . $resolvedParams[2] . ', ' . $resolvedParams[3] . ');');

        return new CompiledExpression('null', 'null', $expression);
    }
}
