<?php

/* GENERATED by scripts/gen-zep.php — DO NOT EDIT. */

namespace Zephir\Optimizers\FunctionCall;

use Zephir\Call;
use Zephir\CompilationContext;
use Zephir\CompiledExpression;
use Zephir\Exception\CompilerException;
use Zephir\Optimizers\OptimizerAbstract;

class MtltextureReplaceRegionMipmapLevelWithBytesBytesPerRowOptimizer extends OptimizerAbstract
{
    public function optimize(array $expression, Call $call, CompilationContext $context)
    {
        if (!isset($expression['parameters']) || count($expression['parameters']) !== 10) {
            throw new CompilerException("'mtltexture_replace_region_mipmap_level_with_bytes_bytes_per_row' requires exactly 10 parameters", $expression);
        }

        $context->headersManager->add('src/mtl-texture');

        $resolvedParams = $call->getReadOnlyResolvedParams($expression['parameters'], $context, $expression);

        return new CompiledExpression(
            'int',
            'mtl_mtltexture_replace_region_mipmap_level_with_bytes_bytes_per_row(' . $resolvedParams[0] . ', ' . $resolvedParams[1] . ', ' . $resolvedParams[2] . ', ' . $resolvedParams[3] . ', ' . $resolvedParams[4] . ', ' . $resolvedParams[5] . ', ' . $resolvedParams[6] . ', ' . $resolvedParams[7] . ', ' . $resolvedParams[8] . ', ' . $resolvedParams[9] . ')',
            $expression
        );
    }
}
