// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Metal\MTL\MTLFunction;

class MTLFunction
{
    public static function name(int handle) -> string
    {
        var result;

        let result = mtlfunction_name(handle);

        return result;
    }

    public static function functionType(int handle) -> int
    {
        return mtlfunction_function_type(handle);
    }

    public static function label(int handle) -> var
    {
        var result;

        let result = mtlfunction_label(handle);

        return result;
    }

    public static function setLabel(int handle, var label) -> void
    {
        mtlfunction_set_label(handle, label);
    }
}
