/* This is a generated file, edit the .stub.php file instead.
 * Stub hash: d0c891c09f506c5f38aeaef798c4b7e6e1ef589b */

ZEND_BEGIN_ARG_INFO_EX(arginfo_class_MTLCompileOptions___construct, 0, 0, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_OBJ_INFO_EX(arginfo_class_MTLCompileOptions_new, 0, 0, MTLCompileOptions, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_class_MTLCompileOptions_pointer, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_class_MTLCompileOptions_fromPointer, 0, 1, IS_STATIC, 0)
	ZEND_ARG_TYPE_INFO(0, pointer, IS_LONG, 0)
ZEND_END_ARG_INFO()

#define arginfo_class_MTLLibrary___construct arginfo_class_MTLCompileOptions___construct

ZEND_BEGIN_ARG_WITH_RETURN_OBJ_INFO_EX(arginfo_class_MTLLibrary_newFunctionWithName, 0, 1, MTLFunction, 1)
	ZEND_ARG_TYPE_INFO(0, name, IS_STRING, 0)
ZEND_END_ARG_INFO()

#define arginfo_class_MTLLibrary_pointer arginfo_class_MTLCompileOptions_pointer

#define arginfo_class_MTLLibrary_fromPointer arginfo_class_MTLCompileOptions_fromPointer

#define arginfo_class_MTLFunction___construct arginfo_class_MTLCompileOptions___construct

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_class_MTLFunction_name, 0, 0, IS_STRING, 0)
ZEND_END_ARG_INFO()

#define arginfo_class_MTLFunction_pointer arginfo_class_MTLCompileOptions_pointer

#define arginfo_class_MTLFunction_fromPointer arginfo_class_MTLCompileOptions_fromPointer

#define arginfo_class_MTLVertexDescriptor___construct arginfo_class_MTLCompileOptions___construct

ZEND_BEGIN_ARG_WITH_RETURN_OBJ_INFO_EX(arginfo_class_MTLVertexDescriptor_vertexDescriptor, 0, 0, MTLVertexDescriptor, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_OBJ_INFO_EX(arginfo_class_MTLVertexDescriptor_attributes, 0, 0, MTLVertexAttributeDescriptorArray, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_OBJ_INFO_EX(arginfo_class_MTLVertexDescriptor_layouts, 0, 0, MTLVertexBufferLayoutDescriptorArray, 0)
ZEND_END_ARG_INFO()

#define arginfo_class_MTLVertexDescriptor_pointer arginfo_class_MTLCompileOptions_pointer

#define arginfo_class_MTLVertexDescriptor_fromPointer arginfo_class_MTLCompileOptions_fromPointer

#define arginfo_class_MTLVertexAttributeDescriptorArray___construct arginfo_class_MTLCompileOptions___construct

ZEND_BEGIN_ARG_WITH_RETURN_OBJ_INFO_EX(arginfo_class_MTLVertexAttributeDescriptorArray_objectAtIndexedSubscript, 0, 1, MTLVertexAttributeDescriptor, 0)
	ZEND_ARG_TYPE_INFO(0, index, IS_LONG, 0)
ZEND_END_ARG_INFO()

#define arginfo_class_MTLVertexAttributeDescriptorArray_pointer arginfo_class_MTLCompileOptions_pointer

#define arginfo_class_MTLVertexAttributeDescriptorArray_fromPointer arginfo_class_MTLCompileOptions_fromPointer

#define arginfo_class_MTLVertexBufferLayoutDescriptorArray___construct arginfo_class_MTLCompileOptions___construct

ZEND_BEGIN_ARG_WITH_RETURN_OBJ_INFO_EX(arginfo_class_MTLVertexBufferLayoutDescriptorArray_objectAtIndexedSubscript, 0, 1, MTLVertexBufferLayoutDescriptor, 0)
	ZEND_ARG_TYPE_INFO(0, index, IS_LONG, 0)
ZEND_END_ARG_INFO()

#define arginfo_class_MTLVertexBufferLayoutDescriptorArray_pointer arginfo_class_MTLCompileOptions_pointer

#define arginfo_class_MTLVertexBufferLayoutDescriptorArray_fromPointer arginfo_class_MTLCompileOptions_fromPointer

#define arginfo_class_MTLVertexAttributeDescriptor___construct arginfo_class_MTLCompileOptions___construct

ZEND_BEGIN_ARG_WITH_RETURN_OBJ_INFO_EX(arginfo_class_MTLVertexAttributeDescriptor_format, 0, 0, MTLVertexFormat, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_class_MTLVertexAttributeDescriptor_setFormat, 0, 1, IS_VOID, 0)
	ZEND_ARG_OBJ_INFO(0, format, MTLVertexFormat, 0)
ZEND_END_ARG_INFO()

#define arginfo_class_MTLVertexAttributeDescriptor_offset arginfo_class_MTLCompileOptions_pointer

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_class_MTLVertexAttributeDescriptor_setOffset, 0, 1, IS_VOID, 0)
	ZEND_ARG_TYPE_INFO(0, offset, IS_LONG, 0)
ZEND_END_ARG_INFO()

#define arginfo_class_MTLVertexAttributeDescriptor_bufferIndex arginfo_class_MTLCompileOptions_pointer

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_class_MTLVertexAttributeDescriptor_setBufferIndex, 0, 1, IS_VOID, 0)
	ZEND_ARG_TYPE_INFO(0, bufferIndex, IS_LONG, 0)
ZEND_END_ARG_INFO()

#define arginfo_class_MTLVertexAttributeDescriptor_pointer arginfo_class_MTLCompileOptions_pointer

#define arginfo_class_MTLVertexAttributeDescriptor_fromPointer arginfo_class_MTLCompileOptions_fromPointer

#define arginfo_class_MTLVertexBufferLayoutDescriptor___construct arginfo_class_MTLCompileOptions___construct

#define arginfo_class_MTLVertexBufferLayoutDescriptor_stride arginfo_class_MTLCompileOptions_pointer

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_class_MTLVertexBufferLayoutDescriptor_setStride, 0, 1, IS_VOID, 0)
	ZEND_ARG_TYPE_INFO(0, stride, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_OBJ_INFO_EX(arginfo_class_MTLVertexBufferLayoutDescriptor_stepFunction, 0, 0, MTLVertexStepFunction, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_class_MTLVertexBufferLayoutDescriptor_setStepFunction, 0, 1, IS_VOID, 0)
	ZEND_ARG_OBJ_INFO(0, stepFunction, MTLVertexStepFunction, 0)
ZEND_END_ARG_INFO()

#define arginfo_class_MTLVertexBufferLayoutDescriptor_pointer arginfo_class_MTLCompileOptions_pointer

#define arginfo_class_MTLVertexBufferLayoutDescriptor_fromPointer arginfo_class_MTLCompileOptions_fromPointer

#define arginfo_class_MTLRenderPipelineDescriptor___construct arginfo_class_MTLCompileOptions___construct

ZEND_BEGIN_ARG_WITH_RETURN_OBJ_INFO_EX(arginfo_class_MTLRenderPipelineDescriptor_new, 0, 0, MTLRenderPipelineDescriptor, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_OBJ_INFO_EX(arginfo_class_MTLRenderPipelineDescriptor_vertexFunction, 0, 0, MTLFunction, 1)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_class_MTLRenderPipelineDescriptor_setVertexFunction, 0, 1, IS_VOID, 0)
	ZEND_ARG_OBJ_INFO(0, function, MTLFunction, 1)
ZEND_END_ARG_INFO()

#define arginfo_class_MTLRenderPipelineDescriptor_fragmentFunction arginfo_class_MTLRenderPipelineDescriptor_vertexFunction

#define arginfo_class_MTLRenderPipelineDescriptor_setFragmentFunction arginfo_class_MTLRenderPipelineDescriptor_setVertexFunction

ZEND_BEGIN_ARG_WITH_RETURN_OBJ_INFO_EX(arginfo_class_MTLRenderPipelineDescriptor_vertexDescriptor, 0, 0, MTLVertexDescriptor, 1)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_class_MTLRenderPipelineDescriptor_setVertexDescriptor, 0, 1, IS_VOID, 0)
	ZEND_ARG_OBJ_INFO(0, vertexDescriptor, MTLVertexDescriptor, 1)
ZEND_END_ARG_INFO()

#define arginfo_class_MTLRenderPipelineDescriptor_rasterSampleCount arginfo_class_MTLCompileOptions_pointer

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_class_MTLRenderPipelineDescriptor_setRasterSampleCount, 0, 1, IS_VOID, 0)
	ZEND_ARG_TYPE_INFO(0, rasterSampleCount, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_OBJ_INFO_EX(arginfo_class_MTLRenderPipelineDescriptor_depthAttachmentPixelFormat, 0, 0, MTLPixelFormat, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_class_MTLRenderPipelineDescriptor_setDepthAttachmentPixelFormat, 0, 1, IS_VOID, 0)
	ZEND_ARG_OBJ_INFO(0, pixelFormat, MTLPixelFormat, 0)
ZEND_END_ARG_INFO()

#define arginfo_class_MTLRenderPipelineDescriptor_stencilAttachmentPixelFormat arginfo_class_MTLRenderPipelineDescriptor_depthAttachmentPixelFormat

#define arginfo_class_MTLRenderPipelineDescriptor_setStencilAttachmentPixelFormat arginfo_class_MTLRenderPipelineDescriptor_setDepthAttachmentPixelFormat

ZEND_BEGIN_ARG_WITH_RETURN_OBJ_INFO_EX(arginfo_class_MTLRenderPipelineDescriptor_colorAttachments, 0, 0, MTLRenderPipelineColorAttachmentDescriptorArray, 0)
ZEND_END_ARG_INFO()

#define arginfo_class_MTLRenderPipelineDescriptor_pointer arginfo_class_MTLCompileOptions_pointer

#define arginfo_class_MTLRenderPipelineDescriptor_fromPointer arginfo_class_MTLCompileOptions_fromPointer

#define arginfo_class_MTLRenderPipelineColorAttachmentDescriptorArray___construct arginfo_class_MTLCompileOptions___construct

ZEND_BEGIN_ARG_WITH_RETURN_OBJ_INFO_EX(arginfo_class_MTLRenderPipelineColorAttachmentDescriptorArray_objectAtIndexedSubscript, 0, 1, MTLRenderPipelineColorAttachmentDescriptor, 0)
	ZEND_ARG_TYPE_INFO(0, index, IS_LONG, 0)
ZEND_END_ARG_INFO()

#define arginfo_class_MTLRenderPipelineColorAttachmentDescriptorArray_pointer arginfo_class_MTLCompileOptions_pointer

#define arginfo_class_MTLRenderPipelineColorAttachmentDescriptorArray_fromPointer arginfo_class_MTLCompileOptions_fromPointer

#define arginfo_class_MTLRenderPipelineColorAttachmentDescriptor___construct arginfo_class_MTLCompileOptions___construct

#define arginfo_class_MTLRenderPipelineColorAttachmentDescriptor_pixelFormat arginfo_class_MTLRenderPipelineDescriptor_depthAttachmentPixelFormat

#define arginfo_class_MTLRenderPipelineColorAttachmentDescriptor_setPixelFormat arginfo_class_MTLRenderPipelineDescriptor_setDepthAttachmentPixelFormat

ZEND_BEGIN_ARG_WITH_RETURN_OBJ_TYPE_MASK_EX(arginfo_class_MTLRenderPipelineColorAttachmentDescriptor_writeMask, 0, 0, MTLColorWriteMask, MAY_BE_LONG)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_class_MTLRenderPipelineColorAttachmentDescriptor_setWriteMask, 0, 1, IS_VOID, 0)
	ZEND_ARG_OBJ_TYPE_MASK(0, writeMask, MTLColorWriteMask, MAY_BE_LONG, NULL)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_class_MTLRenderPipelineColorAttachmentDescriptor_blendingEnabled, 0, 0, _IS_BOOL, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_class_MTLRenderPipelineColorAttachmentDescriptor_setBlendingEnabled, 0, 1, IS_VOID, 0)
	ZEND_ARG_TYPE_INFO(0, blendingEnabled, _IS_BOOL, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_OBJ_INFO_EX(arginfo_class_MTLRenderPipelineColorAttachmentDescriptor_rgbBlendOperation, 0, 0, MTLBlendOperation, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_class_MTLRenderPipelineColorAttachmentDescriptor_setRgbBlendOperation, 0, 1, IS_VOID, 0)
	ZEND_ARG_OBJ_INFO(0, operation, MTLBlendOperation, 0)
ZEND_END_ARG_INFO()

#define arginfo_class_MTLRenderPipelineColorAttachmentDescriptor_alphaBlendOperation arginfo_class_MTLRenderPipelineColorAttachmentDescriptor_rgbBlendOperation

#define arginfo_class_MTLRenderPipelineColorAttachmentDescriptor_setAlphaBlendOperation arginfo_class_MTLRenderPipelineColorAttachmentDescriptor_setRgbBlendOperation

ZEND_BEGIN_ARG_WITH_RETURN_OBJ_INFO_EX(arginfo_class_MTLRenderPipelineColorAttachmentDescriptor_sourceRGBBlendFactor, 0, 0, MTLBlendFactor, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_class_MTLRenderPipelineColorAttachmentDescriptor_setSourceRGBBlendFactor, 0, 1, IS_VOID, 0)
	ZEND_ARG_OBJ_INFO(0, factor, MTLBlendFactor, 0)
ZEND_END_ARG_INFO()

#define arginfo_class_MTLRenderPipelineColorAttachmentDescriptor_destinationRGBBlendFactor arginfo_class_MTLRenderPipelineColorAttachmentDescriptor_sourceRGBBlendFactor

#define arginfo_class_MTLRenderPipelineColorAttachmentDescriptor_setDestinationRGBBlendFactor arginfo_class_MTLRenderPipelineColorAttachmentDescriptor_setSourceRGBBlendFactor

#define arginfo_class_MTLRenderPipelineColorAttachmentDescriptor_sourceAlphaBlendFactor arginfo_class_MTLRenderPipelineColorAttachmentDescriptor_sourceRGBBlendFactor

#define arginfo_class_MTLRenderPipelineColorAttachmentDescriptor_setSourceAlphaBlendFactor arginfo_class_MTLRenderPipelineColorAttachmentDescriptor_setSourceRGBBlendFactor

#define arginfo_class_MTLRenderPipelineColorAttachmentDescriptor_destinationAlphaBlendFactor arginfo_class_MTLRenderPipelineColorAttachmentDescriptor_sourceRGBBlendFactor

#define arginfo_class_MTLRenderPipelineColorAttachmentDescriptor_setDestinationAlphaBlendFactor arginfo_class_MTLRenderPipelineColorAttachmentDescriptor_setSourceRGBBlendFactor

#define arginfo_class_MTLRenderPipelineColorAttachmentDescriptor_pointer arginfo_class_MTLCompileOptions_pointer

#define arginfo_class_MTLRenderPipelineColorAttachmentDescriptor_fromPointer arginfo_class_MTLCompileOptions_fromPointer

#define arginfo_class_MTLRenderPipelineState___construct arginfo_class_MTLCompileOptions___construct

#define arginfo_class_MTLRenderPipelineState_pointer arginfo_class_MTLCompileOptions_pointer

#define arginfo_class_MTLRenderPipelineState_fromPointer arginfo_class_MTLCompileOptions_fromPointer

#define arginfo_class_MTLStencilDescriptor___construct arginfo_class_MTLCompileOptions___construct

ZEND_BEGIN_ARG_WITH_RETURN_OBJ_INFO_EX(arginfo_class_MTLStencilDescriptor_new, 0, 0, MTLStencilDescriptor, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_OBJ_INFO_EX(arginfo_class_MTLStencilDescriptor_stencilCompareFunction, 0, 0, MTLCompareFunction, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_class_MTLStencilDescriptor_setStencilCompareFunction, 0, 1, IS_VOID, 0)
	ZEND_ARG_OBJ_INFO(0, function, MTLCompareFunction, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_OBJ_INFO_EX(arginfo_class_MTLStencilDescriptor_stencilFailureOperation, 0, 0, MTLStencilOperation, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_class_MTLStencilDescriptor_setStencilFailureOperation, 0, 1, IS_VOID, 0)
	ZEND_ARG_OBJ_INFO(0, operation, MTLStencilOperation, 0)
ZEND_END_ARG_INFO()

#define arginfo_class_MTLStencilDescriptor_depthFailureOperation arginfo_class_MTLStencilDescriptor_stencilFailureOperation

#define arginfo_class_MTLStencilDescriptor_setDepthFailureOperation arginfo_class_MTLStencilDescriptor_setStencilFailureOperation

#define arginfo_class_MTLStencilDescriptor_depthStencilPassOperation arginfo_class_MTLStencilDescriptor_stencilFailureOperation

#define arginfo_class_MTLStencilDescriptor_setDepthStencilPassOperation arginfo_class_MTLStencilDescriptor_setStencilFailureOperation

#define arginfo_class_MTLStencilDescriptor_readMask arginfo_class_MTLCompileOptions_pointer

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_class_MTLStencilDescriptor_setReadMask, 0, 1, IS_VOID, 0)
	ZEND_ARG_TYPE_INFO(0, readMask, IS_LONG, 0)
ZEND_END_ARG_INFO()

#define arginfo_class_MTLStencilDescriptor_writeMask arginfo_class_MTLCompileOptions_pointer

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_class_MTLStencilDescriptor_setWriteMask, 0, 1, IS_VOID, 0)
	ZEND_ARG_TYPE_INFO(0, writeMask, IS_LONG, 0)
ZEND_END_ARG_INFO()

#define arginfo_class_MTLStencilDescriptor_pointer arginfo_class_MTLCompileOptions_pointer

#define arginfo_class_MTLStencilDescriptor_fromPointer arginfo_class_MTLCompileOptions_fromPointer

#define arginfo_class_MTLDepthStencilDescriptor___construct arginfo_class_MTLCompileOptions___construct

ZEND_BEGIN_ARG_WITH_RETURN_OBJ_INFO_EX(arginfo_class_MTLDepthStencilDescriptor_new, 0, 0, MTLDepthStencilDescriptor, 0)
ZEND_END_ARG_INFO()

#define arginfo_class_MTLDepthStencilDescriptor_depthCompareFunction arginfo_class_MTLStencilDescriptor_stencilCompareFunction

#define arginfo_class_MTLDepthStencilDescriptor_setDepthCompareFunction arginfo_class_MTLStencilDescriptor_setStencilCompareFunction

#define arginfo_class_MTLDepthStencilDescriptor_depthWriteEnabled arginfo_class_MTLRenderPipelineColorAttachmentDescriptor_blendingEnabled

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_class_MTLDepthStencilDescriptor_setDepthWriteEnabled, 0, 1, IS_VOID, 0)
	ZEND_ARG_TYPE_INFO(0, depthWriteEnabled, _IS_BOOL, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_OBJ_INFO_EX(arginfo_class_MTLDepthStencilDescriptor_frontFaceStencil, 0, 0, MTLStencilDescriptor, 1)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_class_MTLDepthStencilDescriptor_setFrontFaceStencil, 0, 1, IS_VOID, 0)
	ZEND_ARG_OBJ_INFO(0, stencil, MTLStencilDescriptor, 1)
ZEND_END_ARG_INFO()

#define arginfo_class_MTLDepthStencilDescriptor_backFaceStencil arginfo_class_MTLDepthStencilDescriptor_frontFaceStencil

#define arginfo_class_MTLDepthStencilDescriptor_setBackFaceStencil arginfo_class_MTLDepthStencilDescriptor_setFrontFaceStencil

#define arginfo_class_MTLDepthStencilDescriptor_pointer arginfo_class_MTLCompileOptions_pointer

#define arginfo_class_MTLDepthStencilDescriptor_fromPointer arginfo_class_MTLCompileOptions_fromPointer

#define arginfo_class_MTLDepthStencilState___construct arginfo_class_MTLCompileOptions___construct

#define arginfo_class_MTLDepthStencilState_pointer arginfo_class_MTLCompileOptions_pointer

#define arginfo_class_MTLDepthStencilState_fromPointer arginfo_class_MTLCompileOptions_fromPointer

ZEND_METHOD(MTLCompileOptions, __construct);
ZEND_METHOD(MTLCompileOptions, new);
ZEND_METHOD(MTLCompileOptions, pointer);
ZEND_METHOD(MTLCompileOptions, fromPointer);
ZEND_METHOD(MTLLibrary, __construct);
ZEND_METHOD(MTLLibrary, newFunctionWithName);
ZEND_METHOD(MTLLibrary, pointer);
ZEND_METHOD(MTLLibrary, fromPointer);
ZEND_METHOD(MTLFunction, __construct);
ZEND_METHOD(MTLFunction, name);
ZEND_METHOD(MTLFunction, pointer);
ZEND_METHOD(MTLFunction, fromPointer);
ZEND_METHOD(MTLVertexDescriptor, __construct);
ZEND_METHOD(MTLVertexDescriptor, vertexDescriptor);
ZEND_METHOD(MTLVertexDescriptor, attributes);
ZEND_METHOD(MTLVertexDescriptor, layouts);
ZEND_METHOD(MTLVertexDescriptor, pointer);
ZEND_METHOD(MTLVertexDescriptor, fromPointer);
ZEND_METHOD(MTLVertexAttributeDescriptorArray, __construct);
ZEND_METHOD(MTLVertexAttributeDescriptorArray, objectAtIndexedSubscript);
ZEND_METHOD(MTLVertexAttributeDescriptorArray, pointer);
ZEND_METHOD(MTLVertexAttributeDescriptorArray, fromPointer);
ZEND_METHOD(MTLVertexBufferLayoutDescriptorArray, __construct);
ZEND_METHOD(MTLVertexBufferLayoutDescriptorArray, objectAtIndexedSubscript);
ZEND_METHOD(MTLVertexBufferLayoutDescriptorArray, pointer);
ZEND_METHOD(MTLVertexBufferLayoutDescriptorArray, fromPointer);
ZEND_METHOD(MTLVertexAttributeDescriptor, __construct);
ZEND_METHOD(MTLVertexAttributeDescriptor, format);
ZEND_METHOD(MTLVertexAttributeDescriptor, setFormat);
ZEND_METHOD(MTLVertexAttributeDescriptor, offset);
ZEND_METHOD(MTLVertexAttributeDescriptor, setOffset);
ZEND_METHOD(MTLVertexAttributeDescriptor, bufferIndex);
ZEND_METHOD(MTLVertexAttributeDescriptor, setBufferIndex);
ZEND_METHOD(MTLVertexAttributeDescriptor, pointer);
ZEND_METHOD(MTLVertexAttributeDescriptor, fromPointer);
ZEND_METHOD(MTLVertexBufferLayoutDescriptor, __construct);
ZEND_METHOD(MTLVertexBufferLayoutDescriptor, stride);
ZEND_METHOD(MTLVertexBufferLayoutDescriptor, setStride);
ZEND_METHOD(MTLVertexBufferLayoutDescriptor, stepFunction);
ZEND_METHOD(MTLVertexBufferLayoutDescriptor, setStepFunction);
ZEND_METHOD(MTLVertexBufferLayoutDescriptor, pointer);
ZEND_METHOD(MTLVertexBufferLayoutDescriptor, fromPointer);
ZEND_METHOD(MTLRenderPipelineDescriptor, __construct);
ZEND_METHOD(MTLRenderPipelineDescriptor, new);
ZEND_METHOD(MTLRenderPipelineDescriptor, vertexFunction);
ZEND_METHOD(MTLRenderPipelineDescriptor, setVertexFunction);
ZEND_METHOD(MTLRenderPipelineDescriptor, fragmentFunction);
ZEND_METHOD(MTLRenderPipelineDescriptor, setFragmentFunction);
ZEND_METHOD(MTLRenderPipelineDescriptor, vertexDescriptor);
ZEND_METHOD(MTLRenderPipelineDescriptor, setVertexDescriptor);
ZEND_METHOD(MTLRenderPipelineDescriptor, rasterSampleCount);
ZEND_METHOD(MTLRenderPipelineDescriptor, setRasterSampleCount);
ZEND_METHOD(MTLRenderPipelineDescriptor, depthAttachmentPixelFormat);
ZEND_METHOD(MTLRenderPipelineDescriptor, setDepthAttachmentPixelFormat);
ZEND_METHOD(MTLRenderPipelineDescriptor, stencilAttachmentPixelFormat);
ZEND_METHOD(MTLRenderPipelineDescriptor, setStencilAttachmentPixelFormat);
ZEND_METHOD(MTLRenderPipelineDescriptor, colorAttachments);
ZEND_METHOD(MTLRenderPipelineDescriptor, pointer);
ZEND_METHOD(MTLRenderPipelineDescriptor, fromPointer);
ZEND_METHOD(MTLRenderPipelineColorAttachmentDescriptorArray, __construct);
ZEND_METHOD(MTLRenderPipelineColorAttachmentDescriptorArray, objectAtIndexedSubscript);
ZEND_METHOD(MTLRenderPipelineColorAttachmentDescriptorArray, pointer);
ZEND_METHOD(MTLRenderPipelineColorAttachmentDescriptorArray, fromPointer);
ZEND_METHOD(MTLRenderPipelineColorAttachmentDescriptor, __construct);
ZEND_METHOD(MTLRenderPipelineColorAttachmentDescriptor, pixelFormat);
ZEND_METHOD(MTLRenderPipelineColorAttachmentDescriptor, setPixelFormat);
ZEND_METHOD(MTLRenderPipelineColorAttachmentDescriptor, writeMask);
ZEND_METHOD(MTLRenderPipelineColorAttachmentDescriptor, setWriteMask);
ZEND_METHOD(MTLRenderPipelineColorAttachmentDescriptor, blendingEnabled);
ZEND_METHOD(MTLRenderPipelineColorAttachmentDescriptor, setBlendingEnabled);
ZEND_METHOD(MTLRenderPipelineColorAttachmentDescriptor, rgbBlendOperation);
ZEND_METHOD(MTLRenderPipelineColorAttachmentDescriptor, setRgbBlendOperation);
ZEND_METHOD(MTLRenderPipelineColorAttachmentDescriptor, alphaBlendOperation);
ZEND_METHOD(MTLRenderPipelineColorAttachmentDescriptor, setAlphaBlendOperation);
ZEND_METHOD(MTLRenderPipelineColorAttachmentDescriptor, sourceRGBBlendFactor);
ZEND_METHOD(MTLRenderPipelineColorAttachmentDescriptor, setSourceRGBBlendFactor);
ZEND_METHOD(MTLRenderPipelineColorAttachmentDescriptor, destinationRGBBlendFactor);
ZEND_METHOD(MTLRenderPipelineColorAttachmentDescriptor, setDestinationRGBBlendFactor);
ZEND_METHOD(MTLRenderPipelineColorAttachmentDescriptor, sourceAlphaBlendFactor);
ZEND_METHOD(MTLRenderPipelineColorAttachmentDescriptor, setSourceAlphaBlendFactor);
ZEND_METHOD(MTLRenderPipelineColorAttachmentDescriptor, destinationAlphaBlendFactor);
ZEND_METHOD(MTLRenderPipelineColorAttachmentDescriptor, setDestinationAlphaBlendFactor);
ZEND_METHOD(MTLRenderPipelineColorAttachmentDescriptor, pointer);
ZEND_METHOD(MTLRenderPipelineColorAttachmentDescriptor, fromPointer);
ZEND_METHOD(MTLRenderPipelineState, __construct);
ZEND_METHOD(MTLRenderPipelineState, pointer);
ZEND_METHOD(MTLRenderPipelineState, fromPointer);
ZEND_METHOD(MTLStencilDescriptor, __construct);
ZEND_METHOD(MTLStencilDescriptor, new);
ZEND_METHOD(MTLStencilDescriptor, stencilCompareFunction);
ZEND_METHOD(MTLStencilDescriptor, setStencilCompareFunction);
ZEND_METHOD(MTLStencilDescriptor, stencilFailureOperation);
ZEND_METHOD(MTLStencilDescriptor, setStencilFailureOperation);
ZEND_METHOD(MTLStencilDescriptor, depthFailureOperation);
ZEND_METHOD(MTLStencilDescriptor, setDepthFailureOperation);
ZEND_METHOD(MTLStencilDescriptor, depthStencilPassOperation);
ZEND_METHOD(MTLStencilDescriptor, setDepthStencilPassOperation);
ZEND_METHOD(MTLStencilDescriptor, readMask);
ZEND_METHOD(MTLStencilDescriptor, setReadMask);
ZEND_METHOD(MTLStencilDescriptor, writeMask);
ZEND_METHOD(MTLStencilDescriptor, setWriteMask);
ZEND_METHOD(MTLStencilDescriptor, pointer);
ZEND_METHOD(MTLStencilDescriptor, fromPointer);
ZEND_METHOD(MTLDepthStencilDescriptor, __construct);
ZEND_METHOD(MTLDepthStencilDescriptor, new);
ZEND_METHOD(MTLDepthStencilDescriptor, depthCompareFunction);
ZEND_METHOD(MTLDepthStencilDescriptor, setDepthCompareFunction);
ZEND_METHOD(MTLDepthStencilDescriptor, depthWriteEnabled);
ZEND_METHOD(MTLDepthStencilDescriptor, setDepthWriteEnabled);
ZEND_METHOD(MTLDepthStencilDescriptor, frontFaceStencil);
ZEND_METHOD(MTLDepthStencilDescriptor, setFrontFaceStencil);
ZEND_METHOD(MTLDepthStencilDescriptor, backFaceStencil);
ZEND_METHOD(MTLDepthStencilDescriptor, setBackFaceStencil);
ZEND_METHOD(MTLDepthStencilDescriptor, pointer);
ZEND_METHOD(MTLDepthStencilDescriptor, fromPointer);
ZEND_METHOD(MTLDepthStencilState, __construct);
ZEND_METHOD(MTLDepthStencilState, pointer);
ZEND_METHOD(MTLDepthStencilState, fromPointer);

static const zend_function_entry class_MTLCompileOptions_methods[] = {
	ZEND_ME(MTLCompileOptions, __construct, arginfo_class_MTLCompileOptions___construct, ZEND_ACC_PRIVATE)
	ZEND_ME(MTLCompileOptions, new, arginfo_class_MTLCompileOptions_new, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	ZEND_ME(MTLCompileOptions, pointer, arginfo_class_MTLCompileOptions_pointer, ZEND_ACC_PUBLIC)
	ZEND_ME(MTLCompileOptions, fromPointer, arginfo_class_MTLCompileOptions_fromPointer, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	ZEND_FE_END
};

static const zend_function_entry class_MTLLibrary_methods[] = {
	ZEND_ME(MTLLibrary, __construct, arginfo_class_MTLLibrary___construct, ZEND_ACC_PRIVATE)
	ZEND_ME(MTLLibrary, newFunctionWithName, arginfo_class_MTLLibrary_newFunctionWithName, ZEND_ACC_PUBLIC)
	ZEND_ME(MTLLibrary, pointer, arginfo_class_MTLLibrary_pointer, ZEND_ACC_PUBLIC)
	ZEND_ME(MTLLibrary, fromPointer, arginfo_class_MTLLibrary_fromPointer, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	ZEND_FE_END
};

static const zend_function_entry class_MTLFunction_methods[] = {
	ZEND_ME(MTLFunction, __construct, arginfo_class_MTLFunction___construct, ZEND_ACC_PRIVATE)
	ZEND_ME(MTLFunction, name, arginfo_class_MTLFunction_name, ZEND_ACC_PUBLIC)
	ZEND_ME(MTLFunction, pointer, arginfo_class_MTLFunction_pointer, ZEND_ACC_PUBLIC)
	ZEND_ME(MTLFunction, fromPointer, arginfo_class_MTLFunction_fromPointer, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	ZEND_FE_END
};

static const zend_function_entry class_MTLVertexDescriptor_methods[] = {
	ZEND_ME(MTLVertexDescriptor, __construct, arginfo_class_MTLVertexDescriptor___construct, ZEND_ACC_PRIVATE)
	ZEND_ME(MTLVertexDescriptor, vertexDescriptor, arginfo_class_MTLVertexDescriptor_vertexDescriptor, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	ZEND_ME(MTLVertexDescriptor, attributes, arginfo_class_MTLVertexDescriptor_attributes, ZEND_ACC_PUBLIC)
	ZEND_ME(MTLVertexDescriptor, layouts, arginfo_class_MTLVertexDescriptor_layouts, ZEND_ACC_PUBLIC)
	ZEND_ME(MTLVertexDescriptor, pointer, arginfo_class_MTLVertexDescriptor_pointer, ZEND_ACC_PUBLIC)
	ZEND_ME(MTLVertexDescriptor, fromPointer, arginfo_class_MTLVertexDescriptor_fromPointer, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	ZEND_FE_END
};

static const zend_function_entry class_MTLVertexAttributeDescriptorArray_methods[] = {
	ZEND_ME(MTLVertexAttributeDescriptorArray, __construct, arginfo_class_MTLVertexAttributeDescriptorArray___construct, ZEND_ACC_PRIVATE)
	ZEND_ME(MTLVertexAttributeDescriptorArray, objectAtIndexedSubscript, arginfo_class_MTLVertexAttributeDescriptorArray_objectAtIndexedSubscript, ZEND_ACC_PUBLIC)
	ZEND_ME(MTLVertexAttributeDescriptorArray, pointer, arginfo_class_MTLVertexAttributeDescriptorArray_pointer, ZEND_ACC_PUBLIC)
	ZEND_ME(MTLVertexAttributeDescriptorArray, fromPointer, arginfo_class_MTLVertexAttributeDescriptorArray_fromPointer, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	ZEND_FE_END
};

static const zend_function_entry class_MTLVertexBufferLayoutDescriptorArray_methods[] = {
	ZEND_ME(MTLVertexBufferLayoutDescriptorArray, __construct, arginfo_class_MTLVertexBufferLayoutDescriptorArray___construct, ZEND_ACC_PRIVATE)
	ZEND_ME(MTLVertexBufferLayoutDescriptorArray, objectAtIndexedSubscript, arginfo_class_MTLVertexBufferLayoutDescriptorArray_objectAtIndexedSubscript, ZEND_ACC_PUBLIC)
	ZEND_ME(MTLVertexBufferLayoutDescriptorArray, pointer, arginfo_class_MTLVertexBufferLayoutDescriptorArray_pointer, ZEND_ACC_PUBLIC)
	ZEND_ME(MTLVertexBufferLayoutDescriptorArray, fromPointer, arginfo_class_MTLVertexBufferLayoutDescriptorArray_fromPointer, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	ZEND_FE_END
};

static const zend_function_entry class_MTLVertexAttributeDescriptor_methods[] = {
	ZEND_ME(MTLVertexAttributeDescriptor, __construct, arginfo_class_MTLVertexAttributeDescriptor___construct, ZEND_ACC_PRIVATE)
	ZEND_ME(MTLVertexAttributeDescriptor, format, arginfo_class_MTLVertexAttributeDescriptor_format, ZEND_ACC_PUBLIC)
	ZEND_ME(MTLVertexAttributeDescriptor, setFormat, arginfo_class_MTLVertexAttributeDescriptor_setFormat, ZEND_ACC_PUBLIC)
	ZEND_ME(MTLVertexAttributeDescriptor, offset, arginfo_class_MTLVertexAttributeDescriptor_offset, ZEND_ACC_PUBLIC)
	ZEND_ME(MTLVertexAttributeDescriptor, setOffset, arginfo_class_MTLVertexAttributeDescriptor_setOffset, ZEND_ACC_PUBLIC)
	ZEND_ME(MTLVertexAttributeDescriptor, bufferIndex, arginfo_class_MTLVertexAttributeDescriptor_bufferIndex, ZEND_ACC_PUBLIC)
	ZEND_ME(MTLVertexAttributeDescriptor, setBufferIndex, arginfo_class_MTLVertexAttributeDescriptor_setBufferIndex, ZEND_ACC_PUBLIC)
	ZEND_ME(MTLVertexAttributeDescriptor, pointer, arginfo_class_MTLVertexAttributeDescriptor_pointer, ZEND_ACC_PUBLIC)
	ZEND_ME(MTLVertexAttributeDescriptor, fromPointer, arginfo_class_MTLVertexAttributeDescriptor_fromPointer, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	ZEND_FE_END
};

static const zend_function_entry class_MTLVertexBufferLayoutDescriptor_methods[] = {
	ZEND_ME(MTLVertexBufferLayoutDescriptor, __construct, arginfo_class_MTLVertexBufferLayoutDescriptor___construct, ZEND_ACC_PRIVATE)
	ZEND_ME(MTLVertexBufferLayoutDescriptor, stride, arginfo_class_MTLVertexBufferLayoutDescriptor_stride, ZEND_ACC_PUBLIC)
	ZEND_ME(MTLVertexBufferLayoutDescriptor, setStride, arginfo_class_MTLVertexBufferLayoutDescriptor_setStride, ZEND_ACC_PUBLIC)
	ZEND_ME(MTLVertexBufferLayoutDescriptor, stepFunction, arginfo_class_MTLVertexBufferLayoutDescriptor_stepFunction, ZEND_ACC_PUBLIC)
	ZEND_ME(MTLVertexBufferLayoutDescriptor, setStepFunction, arginfo_class_MTLVertexBufferLayoutDescriptor_setStepFunction, ZEND_ACC_PUBLIC)
	ZEND_ME(MTLVertexBufferLayoutDescriptor, pointer, arginfo_class_MTLVertexBufferLayoutDescriptor_pointer, ZEND_ACC_PUBLIC)
	ZEND_ME(MTLVertexBufferLayoutDescriptor, fromPointer, arginfo_class_MTLVertexBufferLayoutDescriptor_fromPointer, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	ZEND_FE_END
};

static const zend_function_entry class_MTLRenderPipelineDescriptor_methods[] = {
	ZEND_ME(MTLRenderPipelineDescriptor, __construct, arginfo_class_MTLRenderPipelineDescriptor___construct, ZEND_ACC_PRIVATE)
	ZEND_ME(MTLRenderPipelineDescriptor, new, arginfo_class_MTLRenderPipelineDescriptor_new, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	ZEND_ME(MTLRenderPipelineDescriptor, vertexFunction, arginfo_class_MTLRenderPipelineDescriptor_vertexFunction, ZEND_ACC_PUBLIC)
	ZEND_ME(MTLRenderPipelineDescriptor, setVertexFunction, arginfo_class_MTLRenderPipelineDescriptor_setVertexFunction, ZEND_ACC_PUBLIC)
	ZEND_ME(MTLRenderPipelineDescriptor, fragmentFunction, arginfo_class_MTLRenderPipelineDescriptor_fragmentFunction, ZEND_ACC_PUBLIC)
	ZEND_ME(MTLRenderPipelineDescriptor, setFragmentFunction, arginfo_class_MTLRenderPipelineDescriptor_setFragmentFunction, ZEND_ACC_PUBLIC)
	ZEND_ME(MTLRenderPipelineDescriptor, vertexDescriptor, arginfo_class_MTLRenderPipelineDescriptor_vertexDescriptor, ZEND_ACC_PUBLIC)
	ZEND_ME(MTLRenderPipelineDescriptor, setVertexDescriptor, arginfo_class_MTLRenderPipelineDescriptor_setVertexDescriptor, ZEND_ACC_PUBLIC)
	ZEND_ME(MTLRenderPipelineDescriptor, rasterSampleCount, arginfo_class_MTLRenderPipelineDescriptor_rasterSampleCount, ZEND_ACC_PUBLIC)
	ZEND_ME(MTLRenderPipelineDescriptor, setRasterSampleCount, arginfo_class_MTLRenderPipelineDescriptor_setRasterSampleCount, ZEND_ACC_PUBLIC)
	ZEND_ME(MTLRenderPipelineDescriptor, depthAttachmentPixelFormat, arginfo_class_MTLRenderPipelineDescriptor_depthAttachmentPixelFormat, ZEND_ACC_PUBLIC)
	ZEND_ME(MTLRenderPipelineDescriptor, setDepthAttachmentPixelFormat, arginfo_class_MTLRenderPipelineDescriptor_setDepthAttachmentPixelFormat, ZEND_ACC_PUBLIC)
	ZEND_ME(MTLRenderPipelineDescriptor, stencilAttachmentPixelFormat, arginfo_class_MTLRenderPipelineDescriptor_stencilAttachmentPixelFormat, ZEND_ACC_PUBLIC)
	ZEND_ME(MTLRenderPipelineDescriptor, setStencilAttachmentPixelFormat, arginfo_class_MTLRenderPipelineDescriptor_setStencilAttachmentPixelFormat, ZEND_ACC_PUBLIC)
	ZEND_ME(MTLRenderPipelineDescriptor, colorAttachments, arginfo_class_MTLRenderPipelineDescriptor_colorAttachments, ZEND_ACC_PUBLIC)
	ZEND_ME(MTLRenderPipelineDescriptor, pointer, arginfo_class_MTLRenderPipelineDescriptor_pointer, ZEND_ACC_PUBLIC)
	ZEND_ME(MTLRenderPipelineDescriptor, fromPointer, arginfo_class_MTLRenderPipelineDescriptor_fromPointer, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	ZEND_FE_END
};

static const zend_function_entry class_MTLRenderPipelineColorAttachmentDescriptorArray_methods[] = {
	ZEND_ME(MTLRenderPipelineColorAttachmentDescriptorArray, __construct, arginfo_class_MTLRenderPipelineColorAttachmentDescriptorArray___construct, ZEND_ACC_PRIVATE)
	ZEND_ME(MTLRenderPipelineColorAttachmentDescriptorArray, objectAtIndexedSubscript, arginfo_class_MTLRenderPipelineColorAttachmentDescriptorArray_objectAtIndexedSubscript, ZEND_ACC_PUBLIC)
	ZEND_ME(MTLRenderPipelineColorAttachmentDescriptorArray, pointer, arginfo_class_MTLRenderPipelineColorAttachmentDescriptorArray_pointer, ZEND_ACC_PUBLIC)
	ZEND_ME(MTLRenderPipelineColorAttachmentDescriptorArray, fromPointer, arginfo_class_MTLRenderPipelineColorAttachmentDescriptorArray_fromPointer, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	ZEND_FE_END
};

static const zend_function_entry class_MTLRenderPipelineColorAttachmentDescriptor_methods[] = {
	ZEND_ME(MTLRenderPipelineColorAttachmentDescriptor, __construct, arginfo_class_MTLRenderPipelineColorAttachmentDescriptor___construct, ZEND_ACC_PRIVATE)
	ZEND_ME(MTLRenderPipelineColorAttachmentDescriptor, pixelFormat, arginfo_class_MTLRenderPipelineColorAttachmentDescriptor_pixelFormat, ZEND_ACC_PUBLIC)
	ZEND_ME(MTLRenderPipelineColorAttachmentDescriptor, setPixelFormat, arginfo_class_MTLRenderPipelineColorAttachmentDescriptor_setPixelFormat, ZEND_ACC_PUBLIC)
	ZEND_ME(MTLRenderPipelineColorAttachmentDescriptor, writeMask, arginfo_class_MTLRenderPipelineColorAttachmentDescriptor_writeMask, ZEND_ACC_PUBLIC)
	ZEND_ME(MTLRenderPipelineColorAttachmentDescriptor, setWriteMask, arginfo_class_MTLRenderPipelineColorAttachmentDescriptor_setWriteMask, ZEND_ACC_PUBLIC)
	ZEND_ME(MTLRenderPipelineColorAttachmentDescriptor, blendingEnabled, arginfo_class_MTLRenderPipelineColorAttachmentDescriptor_blendingEnabled, ZEND_ACC_PUBLIC)
	ZEND_ME(MTLRenderPipelineColorAttachmentDescriptor, setBlendingEnabled, arginfo_class_MTLRenderPipelineColorAttachmentDescriptor_setBlendingEnabled, ZEND_ACC_PUBLIC)
	ZEND_ME(MTLRenderPipelineColorAttachmentDescriptor, rgbBlendOperation, arginfo_class_MTLRenderPipelineColorAttachmentDescriptor_rgbBlendOperation, ZEND_ACC_PUBLIC)
	ZEND_ME(MTLRenderPipelineColorAttachmentDescriptor, setRgbBlendOperation, arginfo_class_MTLRenderPipelineColorAttachmentDescriptor_setRgbBlendOperation, ZEND_ACC_PUBLIC)
	ZEND_ME(MTLRenderPipelineColorAttachmentDescriptor, alphaBlendOperation, arginfo_class_MTLRenderPipelineColorAttachmentDescriptor_alphaBlendOperation, ZEND_ACC_PUBLIC)
	ZEND_ME(MTLRenderPipelineColorAttachmentDescriptor, setAlphaBlendOperation, arginfo_class_MTLRenderPipelineColorAttachmentDescriptor_setAlphaBlendOperation, ZEND_ACC_PUBLIC)
	ZEND_ME(MTLRenderPipelineColorAttachmentDescriptor, sourceRGBBlendFactor, arginfo_class_MTLRenderPipelineColorAttachmentDescriptor_sourceRGBBlendFactor, ZEND_ACC_PUBLIC)
	ZEND_ME(MTLRenderPipelineColorAttachmentDescriptor, setSourceRGBBlendFactor, arginfo_class_MTLRenderPipelineColorAttachmentDescriptor_setSourceRGBBlendFactor, ZEND_ACC_PUBLIC)
	ZEND_ME(MTLRenderPipelineColorAttachmentDescriptor, destinationRGBBlendFactor, arginfo_class_MTLRenderPipelineColorAttachmentDescriptor_destinationRGBBlendFactor, ZEND_ACC_PUBLIC)
	ZEND_ME(MTLRenderPipelineColorAttachmentDescriptor, setDestinationRGBBlendFactor, arginfo_class_MTLRenderPipelineColorAttachmentDescriptor_setDestinationRGBBlendFactor, ZEND_ACC_PUBLIC)
	ZEND_ME(MTLRenderPipelineColorAttachmentDescriptor, sourceAlphaBlendFactor, arginfo_class_MTLRenderPipelineColorAttachmentDescriptor_sourceAlphaBlendFactor, ZEND_ACC_PUBLIC)
	ZEND_ME(MTLRenderPipelineColorAttachmentDescriptor, setSourceAlphaBlendFactor, arginfo_class_MTLRenderPipelineColorAttachmentDescriptor_setSourceAlphaBlendFactor, ZEND_ACC_PUBLIC)
	ZEND_ME(MTLRenderPipelineColorAttachmentDescriptor, destinationAlphaBlendFactor, arginfo_class_MTLRenderPipelineColorAttachmentDescriptor_destinationAlphaBlendFactor, ZEND_ACC_PUBLIC)
	ZEND_ME(MTLRenderPipelineColorAttachmentDescriptor, setDestinationAlphaBlendFactor, arginfo_class_MTLRenderPipelineColorAttachmentDescriptor_setDestinationAlphaBlendFactor, ZEND_ACC_PUBLIC)
	ZEND_ME(MTLRenderPipelineColorAttachmentDescriptor, pointer, arginfo_class_MTLRenderPipelineColorAttachmentDescriptor_pointer, ZEND_ACC_PUBLIC)
	ZEND_ME(MTLRenderPipelineColorAttachmentDescriptor, fromPointer, arginfo_class_MTLRenderPipelineColorAttachmentDescriptor_fromPointer, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	ZEND_FE_END
};

static const zend_function_entry class_MTLRenderPipelineState_methods[] = {
	ZEND_ME(MTLRenderPipelineState, __construct, arginfo_class_MTLRenderPipelineState___construct, ZEND_ACC_PRIVATE)
	ZEND_ME(MTLRenderPipelineState, pointer, arginfo_class_MTLRenderPipelineState_pointer, ZEND_ACC_PUBLIC)
	ZEND_ME(MTLRenderPipelineState, fromPointer, arginfo_class_MTLRenderPipelineState_fromPointer, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	ZEND_FE_END
};

static const zend_function_entry class_MTLStencilDescriptor_methods[] = {
	ZEND_ME(MTLStencilDescriptor, __construct, arginfo_class_MTLStencilDescriptor___construct, ZEND_ACC_PRIVATE)
	ZEND_ME(MTLStencilDescriptor, new, arginfo_class_MTLStencilDescriptor_new, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	ZEND_ME(MTLStencilDescriptor, stencilCompareFunction, arginfo_class_MTLStencilDescriptor_stencilCompareFunction, ZEND_ACC_PUBLIC)
	ZEND_ME(MTLStencilDescriptor, setStencilCompareFunction, arginfo_class_MTLStencilDescriptor_setStencilCompareFunction, ZEND_ACC_PUBLIC)
	ZEND_ME(MTLStencilDescriptor, stencilFailureOperation, arginfo_class_MTLStencilDescriptor_stencilFailureOperation, ZEND_ACC_PUBLIC)
	ZEND_ME(MTLStencilDescriptor, setStencilFailureOperation, arginfo_class_MTLStencilDescriptor_setStencilFailureOperation, ZEND_ACC_PUBLIC)
	ZEND_ME(MTLStencilDescriptor, depthFailureOperation, arginfo_class_MTLStencilDescriptor_depthFailureOperation, ZEND_ACC_PUBLIC)
	ZEND_ME(MTLStencilDescriptor, setDepthFailureOperation, arginfo_class_MTLStencilDescriptor_setDepthFailureOperation, ZEND_ACC_PUBLIC)
	ZEND_ME(MTLStencilDescriptor, depthStencilPassOperation, arginfo_class_MTLStencilDescriptor_depthStencilPassOperation, ZEND_ACC_PUBLIC)
	ZEND_ME(MTLStencilDescriptor, setDepthStencilPassOperation, arginfo_class_MTLStencilDescriptor_setDepthStencilPassOperation, ZEND_ACC_PUBLIC)
	ZEND_ME(MTLStencilDescriptor, readMask, arginfo_class_MTLStencilDescriptor_readMask, ZEND_ACC_PUBLIC)
	ZEND_ME(MTLStencilDescriptor, setReadMask, arginfo_class_MTLStencilDescriptor_setReadMask, ZEND_ACC_PUBLIC)
	ZEND_ME(MTLStencilDescriptor, writeMask, arginfo_class_MTLStencilDescriptor_writeMask, ZEND_ACC_PUBLIC)
	ZEND_ME(MTLStencilDescriptor, setWriteMask, arginfo_class_MTLStencilDescriptor_setWriteMask, ZEND_ACC_PUBLIC)
	ZEND_ME(MTLStencilDescriptor, pointer, arginfo_class_MTLStencilDescriptor_pointer, ZEND_ACC_PUBLIC)
	ZEND_ME(MTLStencilDescriptor, fromPointer, arginfo_class_MTLStencilDescriptor_fromPointer, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	ZEND_FE_END
};

static const zend_function_entry class_MTLDepthStencilDescriptor_methods[] = {
	ZEND_ME(MTLDepthStencilDescriptor, __construct, arginfo_class_MTLDepthStencilDescriptor___construct, ZEND_ACC_PRIVATE)
	ZEND_ME(MTLDepthStencilDescriptor, new, arginfo_class_MTLDepthStencilDescriptor_new, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	ZEND_ME(MTLDepthStencilDescriptor, depthCompareFunction, arginfo_class_MTLDepthStencilDescriptor_depthCompareFunction, ZEND_ACC_PUBLIC)
	ZEND_ME(MTLDepthStencilDescriptor, setDepthCompareFunction, arginfo_class_MTLDepthStencilDescriptor_setDepthCompareFunction, ZEND_ACC_PUBLIC)
	ZEND_ME(MTLDepthStencilDescriptor, depthWriteEnabled, arginfo_class_MTLDepthStencilDescriptor_depthWriteEnabled, ZEND_ACC_PUBLIC)
	ZEND_ME(MTLDepthStencilDescriptor, setDepthWriteEnabled, arginfo_class_MTLDepthStencilDescriptor_setDepthWriteEnabled, ZEND_ACC_PUBLIC)
	ZEND_ME(MTLDepthStencilDescriptor, frontFaceStencil, arginfo_class_MTLDepthStencilDescriptor_frontFaceStencil, ZEND_ACC_PUBLIC)
	ZEND_ME(MTLDepthStencilDescriptor, setFrontFaceStencil, arginfo_class_MTLDepthStencilDescriptor_setFrontFaceStencil, ZEND_ACC_PUBLIC)
	ZEND_ME(MTLDepthStencilDescriptor, backFaceStencil, arginfo_class_MTLDepthStencilDescriptor_backFaceStencil, ZEND_ACC_PUBLIC)
	ZEND_ME(MTLDepthStencilDescriptor, setBackFaceStencil, arginfo_class_MTLDepthStencilDescriptor_setBackFaceStencil, ZEND_ACC_PUBLIC)
	ZEND_ME(MTLDepthStencilDescriptor, pointer, arginfo_class_MTLDepthStencilDescriptor_pointer, ZEND_ACC_PUBLIC)
	ZEND_ME(MTLDepthStencilDescriptor, fromPointer, arginfo_class_MTLDepthStencilDescriptor_fromPointer, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	ZEND_FE_END
};

static const zend_function_entry class_MTLDepthStencilState_methods[] = {
	ZEND_ME(MTLDepthStencilState, __construct, arginfo_class_MTLDepthStencilState___construct, ZEND_ACC_PRIVATE)
	ZEND_ME(MTLDepthStencilState, pointer, arginfo_class_MTLDepthStencilState_pointer, ZEND_ACC_PUBLIC)
	ZEND_ME(MTLDepthStencilState, fromPointer, arginfo_class_MTLDepthStencilState_fromPointer, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	ZEND_FE_END
};

static zend_class_entry *register_class_MTLCompileOptions(void)
{
	zend_class_entry ce, *class_entry;

	INIT_CLASS_ENTRY(ce, "MTLCompileOptions", class_MTLCompileOptions_methods);
	class_entry = zend_register_internal_class_with_flags(&ce, NULL, ZEND_ACC_FINAL|ZEND_ACC_NOT_SERIALIZABLE);

	return class_entry;
}

static zend_class_entry *register_class_MTLLibrary(void)
{
	zend_class_entry ce, *class_entry;

	INIT_CLASS_ENTRY(ce, "MTLLibrary", class_MTLLibrary_methods);
	class_entry = zend_register_internal_class_with_flags(&ce, NULL, ZEND_ACC_FINAL|ZEND_ACC_NOT_SERIALIZABLE);

	return class_entry;
}

static zend_class_entry *register_class_MTLFunction(void)
{
	zend_class_entry ce, *class_entry;

	INIT_CLASS_ENTRY(ce, "MTLFunction", class_MTLFunction_methods);
	class_entry = zend_register_internal_class_with_flags(&ce, NULL, ZEND_ACC_FINAL|ZEND_ACC_NOT_SERIALIZABLE);

	return class_entry;
}

static zend_class_entry *register_class_MTLVertexDescriptor(void)
{
	zend_class_entry ce, *class_entry;

	INIT_CLASS_ENTRY(ce, "MTLVertexDescriptor", class_MTLVertexDescriptor_methods);
	class_entry = zend_register_internal_class_with_flags(&ce, NULL, ZEND_ACC_FINAL|ZEND_ACC_NOT_SERIALIZABLE);

	return class_entry;
}

static zend_class_entry *register_class_MTLVertexAttributeDescriptorArray(void)
{
	zend_class_entry ce, *class_entry;

	INIT_CLASS_ENTRY(ce, "MTLVertexAttributeDescriptorArray", class_MTLVertexAttributeDescriptorArray_methods);
	class_entry = zend_register_internal_class_with_flags(&ce, NULL, ZEND_ACC_FINAL|ZEND_ACC_NOT_SERIALIZABLE);

	return class_entry;
}

static zend_class_entry *register_class_MTLVertexBufferLayoutDescriptorArray(void)
{
	zend_class_entry ce, *class_entry;

	INIT_CLASS_ENTRY(ce, "MTLVertexBufferLayoutDescriptorArray", class_MTLVertexBufferLayoutDescriptorArray_methods);
	class_entry = zend_register_internal_class_with_flags(&ce, NULL, ZEND_ACC_FINAL|ZEND_ACC_NOT_SERIALIZABLE);

	return class_entry;
}

static zend_class_entry *register_class_MTLVertexAttributeDescriptor(void)
{
	zend_class_entry ce, *class_entry;

	INIT_CLASS_ENTRY(ce, "MTLVertexAttributeDescriptor", class_MTLVertexAttributeDescriptor_methods);
	class_entry = zend_register_internal_class_with_flags(&ce, NULL, ZEND_ACC_FINAL|ZEND_ACC_NOT_SERIALIZABLE);

	return class_entry;
}

static zend_class_entry *register_class_MTLVertexBufferLayoutDescriptor(void)
{
	zend_class_entry ce, *class_entry;

	INIT_CLASS_ENTRY(ce, "MTLVertexBufferLayoutDescriptor", class_MTLVertexBufferLayoutDescriptor_methods);
	class_entry = zend_register_internal_class_with_flags(&ce, NULL, ZEND_ACC_FINAL|ZEND_ACC_NOT_SERIALIZABLE);

	return class_entry;
}

static zend_class_entry *register_class_MTLRenderPipelineDescriptor(void)
{
	zend_class_entry ce, *class_entry;

	INIT_CLASS_ENTRY(ce, "MTLRenderPipelineDescriptor", class_MTLRenderPipelineDescriptor_methods);
	class_entry = zend_register_internal_class_with_flags(&ce, NULL, ZEND_ACC_FINAL|ZEND_ACC_NOT_SERIALIZABLE);

	return class_entry;
}

static zend_class_entry *register_class_MTLRenderPipelineColorAttachmentDescriptorArray(void)
{
	zend_class_entry ce, *class_entry;

	INIT_CLASS_ENTRY(ce, "MTLRenderPipelineColorAttachmentDescriptorArray", class_MTLRenderPipelineColorAttachmentDescriptorArray_methods);
	class_entry = zend_register_internal_class_with_flags(&ce, NULL, ZEND_ACC_FINAL|ZEND_ACC_NOT_SERIALIZABLE);

	return class_entry;
}

static zend_class_entry *register_class_MTLRenderPipelineColorAttachmentDescriptor(void)
{
	zend_class_entry ce, *class_entry;

	INIT_CLASS_ENTRY(ce, "MTLRenderPipelineColorAttachmentDescriptor", class_MTLRenderPipelineColorAttachmentDescriptor_methods);
	class_entry = zend_register_internal_class_with_flags(&ce, NULL, ZEND_ACC_FINAL|ZEND_ACC_NOT_SERIALIZABLE);

	return class_entry;
}

static zend_class_entry *register_class_MTLRenderPipelineState(void)
{
	zend_class_entry ce, *class_entry;

	INIT_CLASS_ENTRY(ce, "MTLRenderPipelineState", class_MTLRenderPipelineState_methods);
	class_entry = zend_register_internal_class_with_flags(&ce, NULL, ZEND_ACC_FINAL|ZEND_ACC_NOT_SERIALIZABLE);

	return class_entry;
}

static zend_class_entry *register_class_MTLStencilDescriptor(void)
{
	zend_class_entry ce, *class_entry;

	INIT_CLASS_ENTRY(ce, "MTLStencilDescriptor", class_MTLStencilDescriptor_methods);
	class_entry = zend_register_internal_class_with_flags(&ce, NULL, ZEND_ACC_FINAL|ZEND_ACC_NOT_SERIALIZABLE);

	return class_entry;
}

static zend_class_entry *register_class_MTLDepthStencilDescriptor(void)
{
	zend_class_entry ce, *class_entry;

	INIT_CLASS_ENTRY(ce, "MTLDepthStencilDescriptor", class_MTLDepthStencilDescriptor_methods);
	class_entry = zend_register_internal_class_with_flags(&ce, NULL, ZEND_ACC_FINAL|ZEND_ACC_NOT_SERIALIZABLE);

	return class_entry;
}

static zend_class_entry *register_class_MTLDepthStencilState(void)
{
	zend_class_entry ce, *class_entry;

	INIT_CLASS_ENTRY(ce, "MTLDepthStencilState", class_MTLDepthStencilState_methods);
	class_entry = zend_register_internal_class_with_flags(&ce, NULL, ZEND_ACC_FINAL|ZEND_ACC_NOT_SERIALIZABLE);

	return class_entry;
}
