// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Metal\MTL\MTLCommandEncoder;

class MTLCommandEncoder
{
    public static function endEncoding(int handle) -> void
    {
        mtlcommandencoder_end_encoding(handle);
    }

    public static function label(int handle) -> var
    {
        var result;

        let result = mtlcommandencoder_label(handle);

        return result;
    }

    public static function setLabel(int handle, var label) -> void
    {
        mtlcommandencoder_set_label(handle, label);
    }
}
