# Generated by scripts/prepare-ext.sh — do not edit.
# PHP_ADD_SOURCES_X has no *.m case; these compile via libtool.
MTL_OBJC_CFLAGS = -fobjc-arc -x objective-c -Wno-deprecated-declarations

$(builddir)/src/ca-metallayer.lo: $(srcdir)/src/ca-metallayer.m
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I$(srcdir) -I$(srcdir)/src $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(MTL_OBJC_CFLAGS) -DZEND_COMPILE_DL_EXT=1 -c $(srcdir)/src/ca-metallayer.m -o $@

$(builddir)/src/mtl-blitcommandencoder.lo: $(srcdir)/src/mtl-blitcommandencoder.m
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I$(srcdir) -I$(srcdir)/src $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(MTL_OBJC_CFLAGS) -DZEND_COMPILE_DL_EXT=1 -c $(srcdir)/src/mtl-blitcommandencoder.m -o $@

$(builddir)/src/mtl-bridge.lo: $(srcdir)/src/mtl-bridge.m
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I$(srcdir) -I$(srcdir)/src $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(MTL_OBJC_CFLAGS) -DZEND_COMPILE_DL_EXT=1 -c $(srcdir)/src/mtl-bridge.m -o $@

$(builddir)/src/mtl-buffer.lo: $(srcdir)/src/mtl-buffer.m
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I$(srcdir) -I$(srcdir)/src $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(MTL_OBJC_CFLAGS) -DZEND_COMPILE_DL_EXT=1 -c $(srcdir)/src/mtl-buffer.m -o $@

$(builddir)/src/mtl-commandbuffer.lo: $(srcdir)/src/mtl-commandbuffer.m
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I$(srcdir) -I$(srcdir)/src $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(MTL_OBJC_CFLAGS) -DZEND_COMPILE_DL_EXT=1 -c $(srcdir)/src/mtl-commandbuffer.m -o $@

$(builddir)/src/mtl-commandencoder.lo: $(srcdir)/src/mtl-commandencoder.m
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I$(srcdir) -I$(srcdir)/src $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(MTL_OBJC_CFLAGS) -DZEND_COMPILE_DL_EXT=1 -c $(srcdir)/src/mtl-commandencoder.m -o $@

$(builddir)/src/mtl-commandqueue.lo: $(srcdir)/src/mtl-commandqueue.m
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I$(srcdir) -I$(srcdir)/src $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(MTL_OBJC_CFLAGS) -DZEND_COMPILE_DL_EXT=1 -c $(srcdir)/src/mtl-commandqueue.m -o $@

$(builddir)/src/mtl-computecommandencoder.lo: $(srcdir)/src/mtl-computecommandencoder.m
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I$(srcdir) -I$(srcdir)/src $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(MTL_OBJC_CFLAGS) -DZEND_COMPILE_DL_EXT=1 -c $(srcdir)/src/mtl-computecommandencoder.m -o $@

$(builddir)/src/mtl-computepipeline.lo: $(srcdir)/src/mtl-computepipeline.m
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I$(srcdir) -I$(srcdir)/src $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(MTL_OBJC_CFLAGS) -DZEND_COMPILE_DL_EXT=1 -c $(srcdir)/src/mtl-computepipeline.m -o $@

$(builddir)/src/mtl-depthstencil.lo: $(srcdir)/src/mtl-depthstencil.m
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I$(srcdir) -I$(srcdir)/src $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(MTL_OBJC_CFLAGS) -DZEND_COMPILE_DL_EXT=1 -c $(srcdir)/src/mtl-depthstencil.m -o $@

$(builddir)/src/mtl-device.lo: $(srcdir)/src/mtl-device.m
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I$(srcdir) -I$(srcdir)/src $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(MTL_OBJC_CFLAGS) -DZEND_COMPILE_DL_EXT=1 -c $(srcdir)/src/mtl-device.m -o $@

$(builddir)/src/mtl-library.lo: $(srcdir)/src/mtl-library.m
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I$(srcdir) -I$(srcdir)/src $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(MTL_OBJC_CFLAGS) -DZEND_COMPILE_DL_EXT=1 -c $(srcdir)/src/mtl-library.m -o $@

$(builddir)/src/mtl-rendercommandencoder.lo: $(srcdir)/src/mtl-rendercommandencoder.m
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I$(srcdir) -I$(srcdir)/src $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(MTL_OBJC_CFLAGS) -DZEND_COMPILE_DL_EXT=1 -c $(srcdir)/src/mtl-rendercommandencoder.m -o $@

$(builddir)/src/mtl-renderpass.lo: $(srcdir)/src/mtl-renderpass.m
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I$(srcdir) -I$(srcdir)/src $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(MTL_OBJC_CFLAGS) -DZEND_COMPILE_DL_EXT=1 -c $(srcdir)/src/mtl-renderpass.m -o $@

$(builddir)/src/mtl-renderpipeline.lo: $(srcdir)/src/mtl-renderpipeline.m
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I$(srcdir) -I$(srcdir)/src $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(MTL_OBJC_CFLAGS) -DZEND_COMPILE_DL_EXT=1 -c $(srcdir)/src/mtl-renderpipeline.m -o $@

$(builddir)/src/mtl-sampler.lo: $(srcdir)/src/mtl-sampler.m
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I$(srcdir) -I$(srcdir)/src $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(MTL_OBJC_CFLAGS) -DZEND_COMPILE_DL_EXT=1 -c $(srcdir)/src/mtl-sampler.m -o $@

$(builddir)/src/mtl-texture.lo: $(srcdir)/src/mtl-texture.m
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I$(srcdir) -I$(srcdir)/src $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(MTL_OBJC_CFLAGS) -DZEND_COMPILE_DL_EXT=1 -c $(srcdir)/src/mtl-texture.m -o $@

$(builddir)/src/mtl-vertexdescriptor.lo: $(srcdir)/src/mtl-vertexdescriptor.m
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I$(srcdir) -I$(srcdir)/src $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(MTL_OBJC_CFLAGS) -DZEND_COMPILE_DL_EXT=1 -c $(srcdir)/src/mtl-vertexdescriptor.m -o $@

