
extern zend_class_entry *metal_mtl_mtlvertexbufferlayoutdescriptor_mtlvertexbufferlayoutdescriptor_ce;

ZEPHIR_INIT_CLASS(Metal_MTL_MTLVertexBufferLayoutDescriptor_MTLVertexBufferLayoutDescriptor);

PHP_METHOD(Metal_MTL_MTLVertexBufferLayoutDescriptor_MTLVertexBufferLayoutDescriptor, stride);
PHP_METHOD(Metal_MTL_MTLVertexBufferLayoutDescriptor_MTLVertexBufferLayoutDescriptor, setStride);
PHP_METHOD(Metal_MTL_MTLVertexBufferLayoutDescriptor_MTLVertexBufferLayoutDescriptor, stepFunction);
PHP_METHOD(Metal_MTL_MTLVertexBufferLayoutDescriptor_MTLVertexBufferLayoutDescriptor, setStepFunction);
PHP_METHOD(Metal_MTL_MTLVertexBufferLayoutDescriptor_MTLVertexBufferLayoutDescriptor, stepRate);
PHP_METHOD(Metal_MTL_MTLVertexBufferLayoutDescriptor_MTLVertexBufferLayoutDescriptor, setStepRate);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_metal_mtl_mtlvertexbufferlayoutdescriptor_mtlvertexbufferlayoutdescriptor_stride, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_metal_mtl_mtlvertexbufferlayoutdescriptor_mtlvertexbufferlayoutdescriptor_setstride, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, stride, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_metal_mtl_mtlvertexbufferlayoutdescriptor_mtlvertexbufferlayoutdescriptor_stepfunction, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_metal_mtl_mtlvertexbufferlayoutdescriptor_mtlvertexbufferlayoutdescriptor_setstepfunction, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, stepFunction, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_metal_mtl_mtlvertexbufferlayoutdescriptor_mtlvertexbufferlayoutdescriptor_steprate, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_metal_mtl_mtlvertexbufferlayoutdescriptor_mtlvertexbufferlayoutdescriptor_setsteprate, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, stepRate, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(metal_mtl_mtlvertexbufferlayoutdescriptor_mtlvertexbufferlayoutdescriptor_method_entry) {
	PHP_ME(Metal_MTL_MTLVertexBufferLayoutDescriptor_MTLVertexBufferLayoutDescriptor, stride, arginfo_metal_mtl_mtlvertexbufferlayoutdescriptor_mtlvertexbufferlayoutdescriptor_stride, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Metal_MTL_MTLVertexBufferLayoutDescriptor_MTLVertexBufferLayoutDescriptor, setStride, arginfo_metal_mtl_mtlvertexbufferlayoutdescriptor_mtlvertexbufferlayoutdescriptor_setstride, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Metal_MTL_MTLVertexBufferLayoutDescriptor_MTLVertexBufferLayoutDescriptor, stepFunction, arginfo_metal_mtl_mtlvertexbufferlayoutdescriptor_mtlvertexbufferlayoutdescriptor_stepfunction, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Metal_MTL_MTLVertexBufferLayoutDescriptor_MTLVertexBufferLayoutDescriptor, setStepFunction, arginfo_metal_mtl_mtlvertexbufferlayoutdescriptor_mtlvertexbufferlayoutdescriptor_setstepfunction, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Metal_MTL_MTLVertexBufferLayoutDescriptor_MTLVertexBufferLayoutDescriptor, stepRate, arginfo_metal_mtl_mtlvertexbufferlayoutdescriptor_mtlvertexbufferlayoutdescriptor_steprate, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Metal_MTL_MTLVertexBufferLayoutDescriptor_MTLVertexBufferLayoutDescriptor, setStepRate, arginfo_metal_mtl_mtlvertexbufferlayoutdescriptor_mtlvertexbufferlayoutdescriptor_setsteprate, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
