// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Metal\MTL\MTLRenderCommandEncoder;

class MTLRenderCommandEncoder
{
    public static function setRenderPipelineState(int handle, int pipelineState) -> void
    {
        mtlrendercommandencoder_set_render_pipeline_state(handle, pipelineState);
    }

    public static function setVertexBufferOffsetAtIndex(int handle, int buffer, int offset, int index) -> void
    {
        mtlrendercommandencoder_set_vertex_buffer_offset_at_index(handle, buffer, offset, index);
    }

    public static function setFragmentBufferOffsetAtIndex(int handle, int buffer, int offset, int index) -> void
    {
        mtlrendercommandencoder_set_fragment_buffer_offset_at_index(handle, buffer, offset, index);
    }

    public static function setVertexTextureAtIndex(int handle, int texture, int index) -> void
    {
        mtlrendercommandencoder_set_vertex_texture_at_index(handle, texture, index);
    }

    public static function setFragmentTextureAtIndex(int handle, int texture, int index) -> void
    {
        mtlrendercommandencoder_set_fragment_texture_at_index(handle, texture, index);
    }

    public static function setFragmentSamplerStateAtIndex(int handle, int sampler, int index) -> void
    {
        mtlrendercommandencoder_set_fragment_sampler_state_at_index(handle, sampler, index);
    }

    public static function setViewport(int handle, double originX, double originY, double width, double height, double znear, double zfar) -> void
    {
        mtlrendercommandencoder_set_viewport(handle, originX, originY, width, height, znear, zfar);
    }

    public static function setScissorRect(int handle, int x, int y, int width, int height) -> void
    {
        mtlrendercommandencoder_set_scissor_rect(handle, x, y, width, height);
    }

    public static function setCullMode(int handle, int cullMode) -> void
    {
        mtlrendercommandencoder_set_cull_mode(handle, cullMode);
    }

    public static function setFrontFacingWinding(int handle, int frontFacingWinding) -> void
    {
        mtlrendercommandencoder_set_front_facing_winding(handle, frontFacingWinding);
    }

    public static function setTriangleFillMode(int handle, int fillMode) -> void
    {
        mtlrendercommandencoder_set_triangle_fill_mode(handle, fillMode);
    }

    public static function setDepthStencilState(int handle, int depthStencilState) -> void
    {
        mtlrendercommandencoder_set_depth_stencil_state(handle, depthStencilState);
    }

    public static function drawPrimitivesVertexStartVertexCount(int handle, int primitiveType, int vertexStart, int vertexCount) -> void
    {
        mtlrendercommandencoder_draw_primitives_vertex_start_vertex_count(handle, primitiveType, vertexStart, vertexCount);
    }

    public static function drawPrimitivesVertexStartVertexCountInstanceCount(int handle, int primitiveType, int vertexStart, int vertexCount, int instanceCount) -> void
    {
        mtlrendercommandencoder_draw_primitives_vertex_start_vertex_count_instance_count(handle, primitiveType, vertexStart, vertexCount, instanceCount);
    }

    public static function drawIndexedPrimitivesIndexCountIndexTypeIndexBufferIndexBufferOffset(int handle, int primitiveType, int indexCount, int indexType, int indexBuffer, int indexBufferOffset) -> void
    {
        mtlrendercommandencoder_draw_indexed_primitives_index_count_index_type_index_buffer_index_buffer_offset(handle, primitiveType, indexCount, indexType, indexBuffer, indexBufferOffset);
    }
}
