#!/usr/bin/env bash
#
# Generate the Zephir C sources into ext/ and make the Objective-C extra
# sources compilable. Does not compile the .so itself.
#
#   1. zephir generate
#   2. stage src/*.{h,m} → ext/src/
#   3. write ext/Makefile.frag — one libtool rule per .m
#      (PHP_ADD_SOURCES_X has no *.m case)
#   4. patch ext/config.m4 (strip .m, append .lo, PHP_ADD_BUILD_DIR,
#      PHP_ADD_MAKEFILE_FRAGMENT, replace PHP_EVAL_LIBLINE(-framework …))
#      and verify each patch applied
#   5. fix ZEPHIR_REGISTER_CLASS namespace prefixes (nested NS)
#   6. strip phpize leftovers so PIE never ships host-absolute paths, and
#      config.w32 (Darwin+Linux only law — MSVC can't compile the .m files
#      anyway, so the Windows build config zephir regenerates never ships)
#
# METAL_ROOT   — package root (default: parent of this script)
# ZEPHIR_BIN   — zephir executable (otherwise searched on PATH / composer)

set -Eeuo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="${METAL_ROOT:-$(cd "${SCRIPT_DIR}/.." && pwd)}"
SRC_DIR="${ROOT_DIR}/src"
EXT_DIR="${ROOT_DIR}/ext"

die() {
    echo "prepare-ext: $*" >&2
    exit 1
}

cd "$ROOT_DIR"

# ---------------------------------------------------------------- locate zephir
if [ -n "${ZEPHIR_BIN:-}" ]; then
    ZEPHIR="$ZEPHIR_BIN"
elif command -v zephir >/dev/null 2>&1; then
    ZEPHIR="$(command -v zephir)"
elif [ -x "$HOME/.config/composer/vendor/bin/zephir" ]; then
    ZEPHIR="$HOME/.config/composer/vendor/bin/zephir"
elif [ -x "$HOME/.composer/vendor/bin/zephir" ]; then
    ZEPHIR="$HOME/.composer/vendor/bin/zephir"
else
    die "Zephir not found. Install with: composer global require phalcon/zephir (or set ZEPHIR_BIN)"
fi

[ -d "$SRC_DIR" ] || die "Missing ${SRC_DIR}/"

echo "prepare-ext: using zephir at ${ZEPHIR}"

# -------------------------------------------- drive zephir with a clean PHP CLI
# Herd's php.ini loads metal; that segfaults `zephir generate`.
# php -n disables ini; re-add zephir_parser so the compiler can run.
find_zephir_parser() {
    local ext_dir candidate
    ext_dir="$(php -r 'echo defined("PHP_EXTENSION_DIR") ? PHP_EXTENSION_DIR : "";' 2>/dev/null || true)"
    for candidate in \
        ${ext_dir:+"${ext_dir}/zephir_parser.so"} \
        /opt/homebrew/lib/php/pecl/*/zephir_parser.so \
        "$HOME/Library/Application Support/Herd/config/php/"*/zephir_parser.so
    do
        if [ -f "$candidate" ]; then
            printf '%s' "$candidate"
            return 0
        fi
    done
    return 1
}

zephir_is_php_script() {
    local first
    [ -f "$1" ] || return 1
    first="$(head -n 1 "$1" 2>/dev/null || true)"
    case "$first" in
        *php*) return 0 ;;
    esac
    return 1
}

run_zephir_generate() {
    local parser=""
    # A test stub (plain bash) must be invoked as-is. The real Zephir
    # entrypoint is a PHP script and must run under php -n so Herd's
    # ini cannot load a previous metal.so and segfault generate.
    if ! zephir_is_php_script "$ZEPHIR"; then
        "$ZEPHIR" generate
        return
    fi
    parser="$(find_zephir_parser || true)"
    if [ -n "$parser" ]; then
        echo "prepare-ext: php -n -d extension=${parser}"
        php -n -d "extension=${parser}" "$ZEPHIR" generate
    else
        "$ZEPHIR" generate
    fi
}

echo "prepare-ext: zephir generate"
run_zephir_generate || die "zephir generate failed"

[ -f "${EXT_DIR}/config.m4" ] || die "zephir generate did not produce ${EXT_DIR}/config.m4"

# ------------------------------------------------- stage hand-written ObjC/C
echo "prepare-ext: copy src/ -> ext/src/"
mkdir -p "${EXT_DIR}/src"
shopt -s nullglob
headers=("${SRC_DIR}"/*.h)
impls=("${SRC_DIR}"/*.m)
shopt -u nullglob
[ ${#headers[@]} -gt 0 ] || die "no src/*.h to stage"
cp -f "${headers[@]}" "${EXT_DIR}/src/"
if [ ${#impls[@]} -gt 0 ]; then
    cp -f "${impls[@]}" "${EXT_DIR}/src/"
fi

# ------------------------------------------- Makefile.frag: one rule per .m
write_makefile_frag() {
    local frag="${EXT_DIR}/Makefile.frag"
    local mfile base

    {
        echo "# Generated by scripts/prepare-ext.sh — do not edit."
        echo "# PHP_ADD_SOURCES_X has no *.m case; these compile via libtool."
        echo "MTL_OBJC_CFLAGS = -fobjc-arc -x objective-c -Wno-deprecated-declarations"
        echo
        shopt -s nullglob
        for mfile in "${SRC_DIR}"/*.m; do
            base="$(basename "$mfile" .m)"
            # The recipe line MUST start with a tab.
            printf '%s\n' "\$(builddir)/src/${base}.lo: \$(srcdir)/src/${base}.m"
            printf '\t%s\n' "\$(LIBTOOL) --tag=CC --mode=compile \$(CC) -I. -I\$(srcdir) -I\$(srcdir)/src \$(COMMON_FLAGS) \$(CFLAGS_CLEAN) \$(EXTRA_CFLAGS) \$(MTL_OBJC_CFLAGS) -DZEND_COMPILE_DL_EXT=1 -c \$(srcdir)/src/${base}.m -o \$@"
            echo
        done
        shopt -u nullglob
    } > "$frag"

    shopt -s nullglob
    for mfile in "${SRC_DIR}"/*.m; do
        base="$(basename "$mfile" .m)"
        grep -q "src/${base}\\.lo:" "$frag" || die "Makefile.frag missing libtool rule for ${base}.m"
        # Recipe must be a real tab, not spaces — make is unforgiving.
        grep -q $'\t$(LIBTOOL)' "$frag" || die "Makefile.frag recipe is not tab-indented"
    done
    shopt -u nullglob
    echo "prepare-ext: wrote ${frag}"
}

write_makefile_frag

# ----------------------------------------------------------- patch config.m4
PATCHER="${SCRIPT_DIR}/patch-config-m4.php"
[ -f "$PATCHER" ] || die "missing ${PATCHER}"
php "$PATCHER" "${EXT_DIR}/config.m4" "${EXT_DIR}/src" || die "config.m4 patch failed"

# ------------------------------------------ fix ZEPHIR_REGISTER_CLASS prefixes
#
# Nested namespaces (Metal\Bridge, Metal\NS\NSButton) make Zephir emit
#
#     ZEPHIR_REGISTER_CLASS(Metal\\Bridge, Bridge, metal, bridge, metal_bridge_bridge_method_entry, 0);
#
# The macro builds the class-entry as lower_ns##_##name##_ce → metal_bridge_ce,
# but the header declares metal_bridge_bridge_ce. The method-entry symbol on
# the same line is correct; the right lower_ns is recovered by stripping
# _<name>. Holds at any namespace depth.
fix_register_macro() {
    local file="$1"
    local tmp="${file}.fixed"

    awk '
        /ZEPHIR_REGISTER_CLASS/ && /_method_entry/ {
            line = $0

            if (!match(line, /[A-Za-z0-9_]+_method_entry/)) { print line; next }
            base = substr(line, RSTART, RLENGTH)
            sub(/_method_entry$/, "", base)

            paren = index(line, "(")
            head  = substr(line, 1, paren)
            n     = split(substr(line, paren + 1), arg, ",")
            if (n < 4) { print line; next }

            name = arg[4]
            gsub(/^[ \t]+|[ \t]+$/, "", name)

            correct = base
            sub("_" name "$", "", correct)

            current = arg[3]
            gsub(/^[ \t]+|[ \t]+$/, "", current)
            if (current == correct) { print line; next }

            arg[3] = " " correct

            out = head arg[1]
            for (i = 2; i <= n; i++) { out = out "," arg[i] }
            print out
            next
        }
        { print }
    ' "$file" > "$tmp" && mv "$tmp" "$file"
}

echo "prepare-ext: fixing ZEPHIR_REGISTER_CLASS namespace prefixes"
register_fixed=0
if [ -d "$EXT_DIR" ]; then
    while IFS= read -r generated; do
        before="${generated}.before-register"
        cp "$generated" "$before"
        fix_register_macro "$generated"
        if ! cmp -s "$generated" "$before"; then
            register_fixed=$((register_fixed + 1))
        fi
        rm -f "$before"
    done < <(find "${EXT_DIR}" -name '*.zep.c' 2>/dev/null || true)
fi
echo "prepare-ext: rewrote ${register_fixed} registration site(s)"

# ------------------------------------------------------- clear phpize leftovers
# Generated .zep.c and the staged src/ tree are deliberately kept.
cd "$EXT_DIR"
rm -rf Makefile Makefile.fragments Makefile.objects Makefile.global modules .libs \
    autom4te.cache build configure configure.ac 'configure~' config.h config.h.in \
    'config.h.in~' config.log config.status config.nice libtool run-tests.php \
    install-sh missing mkinstalldirs config.guess config.sub ltmain.sh aclocal.m4 \
    acinclude.m4 config.w32 2>/dev/null || true
find . \( -name '*.lo' -o -name '*.o' -o -name '*.dep' -o -name '*.la' -o -name '*.so' \) \
    -delete 2>/dev/null || true
find . \( -name '.libs' -o -name '*.dSYM' \) -type d -exec rm -rf {} + 2>/dev/null || true
cd "$ROOT_DIR"

echo "prepare-ext: PREPARE_EXT_OK"
