// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Metal\MTL\MTLComputePipelineState;

class MTLComputePipelineState
{
    public static function label(int handle) -> var
    {
        var result;

        let result = mtlcomputepipelinestate_label(handle);

        return result;
    }

    public static function maxTotalThreadsPerThreadgroup(int handle) -> int
    {
        return mtlcomputepipelinestate_max_total_threads_per_threadgroup(handle);
    }

    public static function threadExecutionWidth(int handle) -> int
    {
        return mtlcomputepipelinestate_thread_execution_width(handle);
    }
}
