// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Metal\MTL\MTLSamplerDescriptor;

class MTLSamplerDescriptor
{
    public static function init() -> int
    {
        return mtlsamplerdescriptor_init();
    }

    public static function minFilter(int handle) -> int
    {
        return mtlsamplerdescriptor_min_filter(handle);
    }

    public static function setMinFilter(int handle, int minFilter) -> void
    {
        mtlsamplerdescriptor_set_min_filter(handle, minFilter);
    }

    public static function magFilter(int handle) -> int
    {
        return mtlsamplerdescriptor_mag_filter(handle);
    }

    public static function setMagFilter(int handle, int magFilter) -> void
    {
        mtlsamplerdescriptor_set_mag_filter(handle, magFilter);
    }

    public static function sAddressMode(int handle) -> int
    {
        return mtlsamplerdescriptor_s_address_mode(handle);
    }

    public static function setSAddressMode(int handle, int sAddressMode) -> void
    {
        mtlsamplerdescriptor_set_s_address_mode(handle, sAddressMode);
    }

    public static function tAddressMode(int handle) -> int
    {
        return mtlsamplerdescriptor_t_address_mode(handle);
    }

    public static function setTAddressMode(int handle, int tAddressMode) -> void
    {
        mtlsamplerdescriptor_set_t_address_mode(handle, tAddressMode);
    }

    public static function label(int handle) -> var
    {
        var result;

        let result = mtlsamplerdescriptor_label(handle);

        return result;
    }

    public static function setLabel(int handle, var label) -> void
    {
        mtlsamplerdescriptor_set_label(handle, label);
    }
}
