// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Metal\MTL\MTLCommandBuffer;

class MTLCommandBuffer
{
    public static function renderCommandEncoderWithDescriptor(int handle, int descriptor) -> int
    {
        return mtlcommandbuffer_render_command_encoder_with_descriptor(handle, descriptor);
    }

    public static function computeCommandEncoder(int handle) -> int
    {
        return mtlcommandbuffer_compute_command_encoder(handle);
    }

    public static function blitCommandEncoder(int handle) -> int
    {
        return mtlcommandbuffer_blit_command_encoder(handle);
    }

    public static function presentDrawable(int handle, int drawable) -> void
    {
        mtlcommandbuffer_present_drawable(handle, drawable);
    }

    public static function commit(int handle) -> void
    {
        mtlcommandbuffer_commit(handle);
    }

    public static function waitUntilCompleted(int handle) -> void
    {
        mtlcommandbuffer_wait_until_completed(handle);
    }

    public static function status(int handle) -> int
    {
        return mtlcommandbuffer_status(handle);
    }

    public static function error(int handle) -> int
    {
        return mtlcommandbuffer_error(handle);
    }
}
