
extern zend_class_entry *metal_mtl_mtlrenderpassdepthattachmentdescriptor_mtlrenderpassdepthattachmentdescriptor_ce;

ZEPHIR_INIT_CLASS(Metal_MTL_MTLRenderPassDepthAttachmentDescriptor_MTLRenderPassDepthAttachmentDescriptor);

PHP_METHOD(Metal_MTL_MTLRenderPassDepthAttachmentDescriptor_MTLRenderPassDepthAttachmentDescriptor, clearDepth);
PHP_METHOD(Metal_MTL_MTLRenderPassDepthAttachmentDescriptor_MTLRenderPassDepthAttachmentDescriptor, setClearDepth);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_metal_mtl_mtlrenderpassdepthattachmentdescriptor_mtlrenderpassdepthattachmentdescriptor_cleardepth, 0, 1, IS_DOUBLE, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_metal_mtl_mtlrenderpassdepthattachmentdescriptor_mtlrenderpassdepthattachmentdescriptor_setcleardepth, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, clearDepth, IS_DOUBLE, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(metal_mtl_mtlrenderpassdepthattachmentdescriptor_mtlrenderpassdepthattachmentdescriptor_method_entry) {
	PHP_ME(Metal_MTL_MTLRenderPassDepthAttachmentDescriptor_MTLRenderPassDepthAttachmentDescriptor, clearDepth, arginfo_metal_mtl_mtlrenderpassdepthattachmentdescriptor_mtlrenderpassdepthattachmentdescriptor_cleardepth, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Metal_MTL_MTLRenderPassDepthAttachmentDescriptor_MTLRenderPassDepthAttachmentDescriptor, setClearDepth, arginfo_metal_mtl_mtlrenderpassdepthattachmentdescriptor_mtlrenderpassdepthattachmentdescriptor_setcleardepth, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
