// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Metal\MTL\MTLRenderPassDepthAttachmentDescriptor;

class MTLRenderPassDepthAttachmentDescriptor
{
    public static function clearDepth(int handle) -> double
    {
        return mtlrenderpassdepthattachmentdescriptor_clear_depth(handle);
    }

    public static function setClearDepth(int handle, double clearDepth) -> void
    {
        mtlrenderpassdepthattachmentdescriptor_set_clear_depth(handle, clearDepth);
    }
}
