
extern zend_class_entry *metal_mtl_mtlrenderpipelinecolorattachmentdescriptor_mtlrenderpipelinecolorattachmentdescriptor_ce;

ZEPHIR_INIT_CLASS(Metal_MTL_MTLRenderPipelineColorAttachmentDescriptor_MTLRenderPipelineColorAttachmentDescriptor);

PHP_METHOD(Metal_MTL_MTLRenderPipelineColorAttachmentDescriptor_MTLRenderPipelineColorAttachmentDescriptor, pixelFormat);
PHP_METHOD(Metal_MTL_MTLRenderPipelineColorAttachmentDescriptor_MTLRenderPipelineColorAttachmentDescriptor, setPixelFormat);
PHP_METHOD(Metal_MTL_MTLRenderPipelineColorAttachmentDescriptor_MTLRenderPipelineColorAttachmentDescriptor, blendingEnabled);
PHP_METHOD(Metal_MTL_MTLRenderPipelineColorAttachmentDescriptor_MTLRenderPipelineColorAttachmentDescriptor, setBlendingEnabled);
PHP_METHOD(Metal_MTL_MTLRenderPipelineColorAttachmentDescriptor_MTLRenderPipelineColorAttachmentDescriptor, sourceRGBBlendFactor);
PHP_METHOD(Metal_MTL_MTLRenderPipelineColorAttachmentDescriptor_MTLRenderPipelineColorAttachmentDescriptor, setSourceRGBBlendFactor);
PHP_METHOD(Metal_MTL_MTLRenderPipelineColorAttachmentDescriptor_MTLRenderPipelineColorAttachmentDescriptor, destinationRGBBlendFactor);
PHP_METHOD(Metal_MTL_MTLRenderPipelineColorAttachmentDescriptor_MTLRenderPipelineColorAttachmentDescriptor, setDestinationRGBBlendFactor);
PHP_METHOD(Metal_MTL_MTLRenderPipelineColorAttachmentDescriptor_MTLRenderPipelineColorAttachmentDescriptor, rgbBlendOperation);
PHP_METHOD(Metal_MTL_MTLRenderPipelineColorAttachmentDescriptor_MTLRenderPipelineColorAttachmentDescriptor, setRgbBlendOperation);
PHP_METHOD(Metal_MTL_MTLRenderPipelineColorAttachmentDescriptor_MTLRenderPipelineColorAttachmentDescriptor, sourceAlphaBlendFactor);
PHP_METHOD(Metal_MTL_MTLRenderPipelineColorAttachmentDescriptor_MTLRenderPipelineColorAttachmentDescriptor, setSourceAlphaBlendFactor);
PHP_METHOD(Metal_MTL_MTLRenderPipelineColorAttachmentDescriptor_MTLRenderPipelineColorAttachmentDescriptor, destinationAlphaBlendFactor);
PHP_METHOD(Metal_MTL_MTLRenderPipelineColorAttachmentDescriptor_MTLRenderPipelineColorAttachmentDescriptor, setDestinationAlphaBlendFactor);
PHP_METHOD(Metal_MTL_MTLRenderPipelineColorAttachmentDescriptor_MTLRenderPipelineColorAttachmentDescriptor, alphaBlendOperation);
PHP_METHOD(Metal_MTL_MTLRenderPipelineColorAttachmentDescriptor_MTLRenderPipelineColorAttachmentDescriptor, setAlphaBlendOperation);
PHP_METHOD(Metal_MTL_MTLRenderPipelineColorAttachmentDescriptor_MTLRenderPipelineColorAttachmentDescriptor, writeMask);
PHP_METHOD(Metal_MTL_MTLRenderPipelineColorAttachmentDescriptor_MTLRenderPipelineColorAttachmentDescriptor, setWriteMask);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_metal_mtl_mtlrenderpipelinecolorattachmentdescriptor_mtlrenderpipelinecolorattachmentdescriptor_pixelformat, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_metal_mtl_mtlrenderpipelinecolorattachmentdescriptor_mtlrenderpipelinecolorattachmentdescriptor_setpixelformat, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, pixelFormat, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_metal_mtl_mtlrenderpipelinecolorattachmentdescriptor_mtlrenderpipelinecolorattachmentdescriptor_blendingenabled, 0, 1, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_metal_mtl_mtlrenderpipelinecolorattachmentdescriptor_mtlrenderpipelinecolorattachmentdescriptor_setblendingenabled, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, blendingEnabled, _IS_BOOL, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_metal_mtl_mtlrenderpipelinecolorattachmentdescriptor_mtlrenderpipelinecolorattachmentdescriptor_sourcergbblendfactor, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_metal_mtl_mtlrenderpipelinecolorattachmentdescriptor_mtlrenderpipelinecolorattachmentdescriptor_setsourcergbblendfactor, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, sourceRGBBlendFactor, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_metal_mtl_mtlrenderpipelinecolorattachmentdescriptor_mtlrenderpipelinecolorattachmentdescriptor_destinationrgbblendfactor, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_metal_mtl_mtlrenderpipelinecolorattachmentdescriptor_mtlrenderpipelinecolorattachmentdescriptor_setdestinationrgbblendfactor, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, destinationRGBBlendFactor, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_metal_mtl_mtlrenderpipelinecolorattachmentdescriptor_mtlrenderpipelinecolorattachmentdescriptor_rgbblendoperation, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_metal_mtl_mtlrenderpipelinecolorattachmentdescriptor_mtlrenderpipelinecolorattachmentdescriptor_setrgbblendoperation, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, rgbBlendOperation, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_metal_mtl_mtlrenderpipelinecolorattachmentdescriptor_mtlrenderpipelinecolorattachmentdescriptor_sourcealphablendfactor, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_metal_mtl_mtlrenderpipelinecolorattachmentdescriptor_mtlrenderpipelinecolorattachmentdescriptor_setsourcealphablendfactor, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, sourceAlphaBlendFactor, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_metal_mtl_mtlrenderpipelinecolorattachmentdescriptor_mtlrenderpipelinecolorattachmentdescriptor_destinationalphablendfactor, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_metal_mtl_mtlrenderpipelinecolorattachmentdescriptor_mtlrenderpipelinecolorattachmentdescriptor_setdestinationalphablendfactor, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, destinationAlphaBlendFactor, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_metal_mtl_mtlrenderpipelinecolorattachmentdescriptor_mtlrenderpipelinecolorattachmentdescriptor_alphablendoperation, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_metal_mtl_mtlrenderpipelinecolorattachmentdescriptor_mtlrenderpipelinecolorattachmentdescriptor_setalphablendoperation, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, alphaBlendOperation, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_metal_mtl_mtlrenderpipelinecolorattachmentdescriptor_mtlrenderpipelinecolorattachmentdescriptor_writemask, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_metal_mtl_mtlrenderpipelinecolorattachmentdescriptor_mtlrenderpipelinecolorattachmentdescriptor_setwritemask, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, writeMask, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(metal_mtl_mtlrenderpipelinecolorattachmentdescriptor_mtlrenderpipelinecolorattachmentdescriptor_method_entry) {
	PHP_ME(Metal_MTL_MTLRenderPipelineColorAttachmentDescriptor_MTLRenderPipelineColorAttachmentDescriptor, pixelFormat, arginfo_metal_mtl_mtlrenderpipelinecolorattachmentdescriptor_mtlrenderpipelinecolorattachmentdescriptor_pixelformat, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Metal_MTL_MTLRenderPipelineColorAttachmentDescriptor_MTLRenderPipelineColorAttachmentDescriptor, setPixelFormat, arginfo_metal_mtl_mtlrenderpipelinecolorattachmentdescriptor_mtlrenderpipelinecolorattachmentdescriptor_setpixelformat, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Metal_MTL_MTLRenderPipelineColorAttachmentDescriptor_MTLRenderPipelineColorAttachmentDescriptor, blendingEnabled, arginfo_metal_mtl_mtlrenderpipelinecolorattachmentdescriptor_mtlrenderpipelinecolorattachmentdescriptor_blendingenabled, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Metal_MTL_MTLRenderPipelineColorAttachmentDescriptor_MTLRenderPipelineColorAttachmentDescriptor, setBlendingEnabled, arginfo_metal_mtl_mtlrenderpipelinecolorattachmentdescriptor_mtlrenderpipelinecolorattachmentdescriptor_setblendingenabled, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Metal_MTL_MTLRenderPipelineColorAttachmentDescriptor_MTLRenderPipelineColorAttachmentDescriptor, sourceRGBBlendFactor, arginfo_metal_mtl_mtlrenderpipelinecolorattachmentdescriptor_mtlrenderpipelinecolorattachmentdescriptor_sourcergbblendfactor, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Metal_MTL_MTLRenderPipelineColorAttachmentDescriptor_MTLRenderPipelineColorAttachmentDescriptor, setSourceRGBBlendFactor, arginfo_metal_mtl_mtlrenderpipelinecolorattachmentdescriptor_mtlrenderpipelinecolorattachmentdescriptor_setsourcergbblendfactor, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Metal_MTL_MTLRenderPipelineColorAttachmentDescriptor_MTLRenderPipelineColorAttachmentDescriptor, destinationRGBBlendFactor, arginfo_metal_mtl_mtlrenderpipelinecolorattachmentdescriptor_mtlrenderpipelinecolorattachmentdescriptor_destinationrgbblendfactor, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Metal_MTL_MTLRenderPipelineColorAttachmentDescriptor_MTLRenderPipelineColorAttachmentDescriptor, setDestinationRGBBlendFactor, arginfo_metal_mtl_mtlrenderpipelinecolorattachmentdescriptor_mtlrenderpipelinecolorattachmentdescriptor_setdestinationrgbblendfactor, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Metal_MTL_MTLRenderPipelineColorAttachmentDescriptor_MTLRenderPipelineColorAttachmentDescriptor, rgbBlendOperation, arginfo_metal_mtl_mtlrenderpipelinecolorattachmentdescriptor_mtlrenderpipelinecolorattachmentdescriptor_rgbblendoperation, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Metal_MTL_MTLRenderPipelineColorAttachmentDescriptor_MTLRenderPipelineColorAttachmentDescriptor, setRgbBlendOperation, arginfo_metal_mtl_mtlrenderpipelinecolorattachmentdescriptor_mtlrenderpipelinecolorattachmentdescriptor_setrgbblendoperation, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Metal_MTL_MTLRenderPipelineColorAttachmentDescriptor_MTLRenderPipelineColorAttachmentDescriptor, sourceAlphaBlendFactor, arginfo_metal_mtl_mtlrenderpipelinecolorattachmentdescriptor_mtlrenderpipelinecolorattachmentdescriptor_sourcealphablendfactor, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Metal_MTL_MTLRenderPipelineColorAttachmentDescriptor_MTLRenderPipelineColorAttachmentDescriptor, setSourceAlphaBlendFactor, arginfo_metal_mtl_mtlrenderpipelinecolorattachmentdescriptor_mtlrenderpipelinecolorattachmentdescriptor_setsourcealphablendfactor, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Metal_MTL_MTLRenderPipelineColorAttachmentDescriptor_MTLRenderPipelineColorAttachmentDescriptor, destinationAlphaBlendFactor, arginfo_metal_mtl_mtlrenderpipelinecolorattachmentdescriptor_mtlrenderpipelinecolorattachmentdescriptor_destinationalphablendfactor, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Metal_MTL_MTLRenderPipelineColorAttachmentDescriptor_MTLRenderPipelineColorAttachmentDescriptor, setDestinationAlphaBlendFactor, arginfo_metal_mtl_mtlrenderpipelinecolorattachmentdescriptor_mtlrenderpipelinecolorattachmentdescriptor_setdestinationalphablendfactor, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Metal_MTL_MTLRenderPipelineColorAttachmentDescriptor_MTLRenderPipelineColorAttachmentDescriptor, alphaBlendOperation, arginfo_metal_mtl_mtlrenderpipelinecolorattachmentdescriptor_mtlrenderpipelinecolorattachmentdescriptor_alphablendoperation, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Metal_MTL_MTLRenderPipelineColorAttachmentDescriptor_MTLRenderPipelineColorAttachmentDescriptor, setAlphaBlendOperation, arginfo_metal_mtl_mtlrenderpipelinecolorattachmentdescriptor_mtlrenderpipelinecolorattachmentdescriptor_setalphablendoperation, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Metal_MTL_MTLRenderPipelineColorAttachmentDescriptor_MTLRenderPipelineColorAttachmentDescriptor, writeMask, arginfo_metal_mtl_mtlrenderpipelinecolorattachmentdescriptor_mtlrenderpipelinecolorattachmentdescriptor_writemask, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Metal_MTL_MTLRenderPipelineColorAttachmentDescriptor_MTLRenderPipelineColorAttachmentDescriptor, setWriteMask, arginfo_metal_mtl_mtlrenderpipelinecolorattachmentdescriptor_mtlrenderpipelinecolorattachmentdescriptor_setwritemask, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
