
extern zend_class_entry *metal_mtl_mtlrenderpipelinecolorattachmentdescriptor_mtlrenderpipelinecolorattachmentdescriptor_ce;

ZEPHIR_INIT_CLASS(Metal_MTL_MTLRenderPipelineColorAttachmentDescriptor_MTLRenderPipelineColorAttachmentDescriptor);

PHP_METHOD(Metal_MTL_MTLRenderPipelineColorAttachmentDescriptor_MTLRenderPipelineColorAttachmentDescriptor, pixelFormat);
PHP_METHOD(Metal_MTL_MTLRenderPipelineColorAttachmentDescriptor_MTLRenderPipelineColorAttachmentDescriptor, setPixelFormat);
PHP_METHOD(Metal_MTL_MTLRenderPipelineColorAttachmentDescriptor_MTLRenderPipelineColorAttachmentDescriptor, blendingEnabled);
PHP_METHOD(Metal_MTL_MTLRenderPipelineColorAttachmentDescriptor_MTLRenderPipelineColorAttachmentDescriptor, setBlendingEnabled);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_metal_mtl_mtlrenderpipelinecolorattachmentdescriptor_mtlrenderpipelinecolorattachmentdescriptor_pixelformat, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_metal_mtl_mtlrenderpipelinecolorattachmentdescriptor_mtlrenderpipelinecolorattachmentdescriptor_setpixelformat, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, pixelFormat, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_metal_mtl_mtlrenderpipelinecolorattachmentdescriptor_mtlrenderpipelinecolorattachmentdescriptor_blendingenabled, 0, 1, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_metal_mtl_mtlrenderpipelinecolorattachmentdescriptor_mtlrenderpipelinecolorattachmentdescriptor_setblendingenabled, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, blendingEnabled, _IS_BOOL, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(metal_mtl_mtlrenderpipelinecolorattachmentdescriptor_mtlrenderpipelinecolorattachmentdescriptor_method_entry) {
	PHP_ME(Metal_MTL_MTLRenderPipelineColorAttachmentDescriptor_MTLRenderPipelineColorAttachmentDescriptor, pixelFormat, arginfo_metal_mtl_mtlrenderpipelinecolorattachmentdescriptor_mtlrenderpipelinecolorattachmentdescriptor_pixelformat, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Metal_MTL_MTLRenderPipelineColorAttachmentDescriptor_MTLRenderPipelineColorAttachmentDescriptor, setPixelFormat, arginfo_metal_mtl_mtlrenderpipelinecolorattachmentdescriptor_mtlrenderpipelinecolorattachmentdescriptor_setpixelformat, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Metal_MTL_MTLRenderPipelineColorAttachmentDescriptor_MTLRenderPipelineColorAttachmentDescriptor, blendingEnabled, arginfo_metal_mtl_mtlrenderpipelinecolorattachmentdescriptor_mtlrenderpipelinecolorattachmentdescriptor_blendingenabled, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Metal_MTL_MTLRenderPipelineColorAttachmentDescriptor_MTLRenderPipelineColorAttachmentDescriptor, setBlendingEnabled, arginfo_metal_mtl_mtlrenderpipelinecolorattachmentdescriptor_mtlrenderpipelinecolorattachmentdescriptor_setblendingenabled, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
