// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Metal\QuartzCore\CAMetalLayer;

class CAMetalLayer
{
    public static function init() -> int
    {
        return cametallayer_init();
    }

    public static function device(int handle) -> int
    {
        return cametallayer_device(handle);
    }

    public static function setDevice(int handle, int device) -> void
    {
        cametallayer_set_device(handle, device);
    }

    public static function pixelFormat(int handle) -> int
    {
        return cametallayer_pixel_format(handle);
    }

    public static function setPixelFormat(int handle, int pixelFormat) -> void
    {
        cametallayer_set_pixel_format(handle, pixelFormat);
    }

    public static function drawableSize(int handle) -> array
    {
        var result;

        let result = cametallayer_drawable_size(handle);

        return result;
    }

    public static function setDrawableSize(int handle, double width, double height) -> void
    {
        cametallayer_set_drawable_size(handle, width, height);
    }

    public static function framebufferOnly(int handle) -> bool
    {
        int r;

        let r = cametallayer_framebuffer_only(handle);

        return r == 1;
    }

    public static function setFramebufferOnly(int handle, bool framebufferOnly) -> void
    {
        cametallayer_set_framebuffer_only(handle, framebufferOnly);
    }

    public static function nextDrawable(int handle) -> int
    {
        return cametallayer_next_drawable(handle);
    }
}
