
extern zend_class_entry *metal_mtl_mtlvertexbufferlayoutdescriptorarray_mtlvertexbufferlayoutdescriptorarray_ce;

ZEPHIR_INIT_CLASS(Metal_MTL_MTLVertexBufferLayoutDescriptorArray_MTLVertexBufferLayoutDescriptorArray);

PHP_METHOD(Metal_MTL_MTLVertexBufferLayoutDescriptorArray_MTLVertexBufferLayoutDescriptorArray, objectAtIndexedSubscript);
PHP_METHOD(Metal_MTL_MTLVertexBufferLayoutDescriptorArray_MTLVertexBufferLayoutDescriptorArray, setObjectAtIndexedSubscript);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_metal_mtl_mtlvertexbufferlayoutdescriptorarray_mtlvertexbufferlayoutdescriptorarray_objectatindexedsubscript, 0, 2, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, index, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_metal_mtl_mtlvertexbufferlayoutdescriptorarray_mtlvertexbufferlayoutdescriptorarray_setobjectatindexedsubscript, 0, 3, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, bufferDesc, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, index, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(metal_mtl_mtlvertexbufferlayoutdescriptorarray_mtlvertexbufferlayoutdescriptorarray_method_entry) {
	PHP_ME(Metal_MTL_MTLVertexBufferLayoutDescriptorArray_MTLVertexBufferLayoutDescriptorArray, objectAtIndexedSubscript, arginfo_metal_mtl_mtlvertexbufferlayoutdescriptorarray_mtlvertexbufferlayoutdescriptorarray_objectatindexedsubscript, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Metal_MTL_MTLVertexBufferLayoutDescriptorArray_MTLVertexBufferLayoutDescriptorArray, setObjectAtIndexedSubscript, arginfo_metal_mtl_mtlvertexbufferlayoutdescriptorarray_mtlvertexbufferlayoutdescriptorarray_setobjectatindexedsubscript, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
