// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Metal\MTL\MTLDepthStencilDescriptor;

class MTLDepthStencilDescriptor
{
    public static function init() -> int
    {
        return mtldepthstencildescriptor_init();
    }

    public static function depthCompareFunction(int handle) -> int
    {
        return mtldepthstencildescriptor_depth_compare_function(handle);
    }

    public static function setDepthCompareFunction(int handle, int depthCompareFunction) -> void
    {
        mtldepthstencildescriptor_set_depth_compare_function(handle, depthCompareFunction);
    }

    public static function depthWriteEnabled(int handle) -> bool
    {
        int r;

        let r = mtldepthstencildescriptor_depth_write_enabled(handle);

        return r == 1;
    }

    public static function setDepthWriteEnabled(int handle, bool depthWriteEnabled) -> void
    {
        mtldepthstencildescriptor_set_depth_write_enabled(handle, depthWriteEnabled);
    }

    public static function label(int handle) -> var
    {
        var result;

        let result = mtldepthstencildescriptor_label(handle);

        return result;
    }

    public static function setLabel(int handle, var label) -> void
    {
        mtldepthstencildescriptor_set_label(handle, label);
    }
}
