// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Metal\MTL\MTLLibrary;

class MTLLibrary
{
    public static function newFunctionWithName(int handle, string functionName) -> int
    {
        return mtllibrary_new_function_with_name(handle, functionName);
    }

    public static function functionNames(int handle) -> array
    {
        var result;

        let result = mtllibrary_function_names(handle);

        return result;
    }

    public static function label(int handle) -> var
    {
        var result;

        let result = mtllibrary_label(handle);

        return result;
    }

    public static function setLabel(int handle, var label) -> void
    {
        mtllibrary_set_label(handle, label);
    }
}
